// pasm - src/shr/ins.rs
// ---------------------
// made by matissoss
// licensed under MPL 2.0

use crate::shr;
use shr::size::Size;

#[cfg(not(feature = "refresh"))]
use shr::ins_switch;

#[cfg(not(feature = "refresh"))]
use std::str::FromStr;

#[rustfmt::skip]
#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Mnemonic {
    MOV  , ADD , SUB ,
    IMUL , MUL , DIV ,
    IDIV , AND , OR  ,
    NOT  , NEG , XOR ,
    SHR  , SAR , SHL ,
    SAL  , LEA , INC ,
    DEC  , CMP , TEST,
    
    JMP, CALL,

    SYSCALL, RET,
    NOP,

    POP   , POPF  , POPFD,
    POPFQ , PUSH  , PUSHF,
    PUSHFD, PUSHFQ,

    CPUID,
    
    // Jcc
    JA, JC, JE, JZ, JL,
    JG, JO, JP, JS, JB,
    
    JAE, JBE, JNZ, JNE,
    JNO, JNP, JNS, JPE,
    JPO, JLE, JGE, JNA,
    JNB, JNC, JNL, JNG,
    
    JNAE, JNBE, JNGE, JNLE,

    // CMOVcc
    CMOVA, CMOVB, CMOVC, CMOVE, CMOVG,
    CMOVL, CMOVO, CMOVP, CMOVS, CMOVZ,

    CMOVAE, CMOVBE, CMOVGE, CMOVLE, CMOVNA,
    CMOVNB, CMOVNC, CMOVNE, CMOVNG, CMOVNL,
    CMOVNO, CMOVNP, CMOVNS, CMOVNZ, CMOVPE, CMOVPO,
    
    CMOVNBE, CMOVNAE, CMOVNGE,CMOVNLE,

    // SSE extension
    ADDPS  , ADDSS,
    SUBPS  , SUBSS,
    MULPS  , MULSS,
    DIVPS  , DIVSS,
    RCPPS  , RCPSS,
    SQRTPS , SQRTSS,
    RSQRTPS, RSQRTSS,
    MINPS  , MINSS,
    MAXPS  , MAXSS,

    ORPS   , ANDPS,
    ANDNPS , XORPS,
    CMPPS  , CMPSS,

    COMISS , UCOMISS,

    SHUFPS, UNPCKLPS, UNPCKHPS,

    MOVAPS, MOVUPS, MOVSS,
    MOVLPS, MOVHPS,
    
    MOVLHPS,MOVHLPS,
    
    // SSE2 extension
    ADDPD  , ADDSD,
    SUBPD  , SUBSD,
    MULPD  , MULSD,
    DIVPD  , DIVSD,
    SQRTPD , SQRTSD,
    MINPD  , MINSD,
    MAXPD  , MAXSD,
    ORPD   , ANDPD,
    ANDNPD , XORPD,

    CMPPD  , CMPSD,
    COMISD , UCOMISD,

    MOVAPD , MOVUPD,
    MOVHPD , MOVLPD,
    MOVSD  , MOVMSKPD,

    MOVDQA , MOVQ2DQ,
    MOVDQ2Q,

    PSUBQ  , PSHUFD    , PSLLDQ,
    PSRLDQ , PMULUDQ   , PSHUFLW,
    PSHUFHW, PUNPCKHQDQ, PUNPCKLQDQ,

    MASKMOVDQU,

    MFENCE , LFENCE , CLFLUSH, PAUSE,
    MOVNTPD, MOVNTDQ, MOVNTI,

    // SSE3 extension
    ADDSUBPS, ADDSUBPD,

    HADDPS, HSUBPS,
    HADDPD, HSUBPD,
    MOVSLDUP, MOVSHDUP,
    MOVDDUP, LDDQU,
    MONITOR, MWAIT,

    // SSSE3 extension

    PABSW, PABSD, PABSB,
    PSIGNW, PSIGND, PSIGNB, PHSUBW,
    PHSUBD, PHADDW, PHADDD, PSHUFB, PHSUBSW,
    PHADDSW, PALIGNR, PMULHRSW, PMADDUBSW,

    // MMX extension
    MOVD  , MOVQ,
    PADDB , PADDW  , PADDD  , PADDQ  ,
    PADDSB, PADDSW , PADDUSB, PADDUSW,
    PSUBB , PSUBW  , PSUBD  , PSUBSB ,
    PSUBSW, PSUBUSB, PSUBUSW, PANDN  ,
    PMULHW, PMULLW,
    PMADDWD,
    PCMPEQB, PCMPEQW, PCMPEQD,
    PCMPGTB, PCMPGTW, PCMPGTD,
    PACKUSWB, PACKSSWB, PACKSSDW,
    PUNPCKLBW, PUNPCKLWD, PUNPCKLDQ,
    PUNPCKHBW, PUNPCKHWD, PUNPCKHDQ,
    POR, PAND, PXOR,
    PSLLW, PSLLD, PSLLQ,
    PSRLW, PSRLD, PSRLQ,
    PSRAW, PSRAD,

    EMMS,

    // SSE4_1 and SSE4_2
    DPPS, DPPD,
    
    PTEST, CRC32,
    
    PEXTRB, PEXTRW, PEXTRD, PEXTRQ,
    PINSRB, PINSRD, PINSRQ, PMAXSB,
    PMAXSD, PMAXUW, PMINSB, PMINSD,
    PMINUW,
    PMULDQ, PMULLD, POPCNT,
    
    BLENDPS, BLENDPD, PBLENDW, PCMPEQQ,
    ROUNDPD, ROUNDPS, ROUNDSD, ROUNDSS,
    MPSADBW, PCMPGTQ,
    
    BLENDVPS, BLENDVPD, PBLENDVB, INSERTPS,
    PACKUSDW, PCMPESTRI,
    MOVNTDQA,

    EXTRACTPS, PCMPESTRM, PCMPISTRI, PCMPISTRM,
    
    PHMINPOSUW,

    // AVX/AVX2
    // ---
    // AVX support roadmap:
    //  - [x] SSE/MMX derived
    //  - [x] avx-part2x
    //  - [x] FMA/AES
    //  - [x] conversions
    // hopefully i can finish before end of 31.05.2025 (spoiler: i did it :D)
    // ---
    // derived from SSE
    VMOVAPS , VMOVUPS, 
    VADDPS  , VADDSS,
    VSUBPS  , VSUBSS,
    VMULPS  , VMULSS,
    VDIVPS  , VDIVSS,
    VRCPPS  , VRCPSS,
    VSQRTPS , VSQRTSS,
    VRSQRTPS, VRSQRTSS,
    VMINPS  , VMINSS,
    VMAXPS  , VMAXSS,

    VORPS   , VANDPS,
    VANDNPS , VXORPS,
    VCMPPS  , VCMPSS,

    VCOMISS , VUCOMISS,

    VSHUFPS, VUNPCKLPS, VUNPCKHPS,

    VMOVSS, VMOVLPS, VMOVHPS,
    
    VMOVLHPS,VMOVHLPS,

    // derived from SSE2
    VADDPD  , VADDSD,
    VSUBPD  , VSUBSD,
    VMULPD  , VMULSD,
    VDIVPD  , VDIVSD,
    VSQRTPD , VSQRTSD,
    VMINPD  , VMINSD,
    VMAXPD  , VMAXSD,
    VORPD   , VANDPD,
    VANDNPD , VXORPD,

    VCMPPD  , VCMPSD,
    VCOMISD , VUCOMISD,

    VMOVAPD , VMOVUPD,
    VMOVHPD , VMOVLPD,
    VMOVSD  , VMOVMSKPD,

    VMOVDQA,
    
    // derived from SSE3 extension
    VADDSUBPS, VADDSUBPD,

    VHADDPS, VHSUBPS,
    VHADDPD, VHSUBPD,
    VMOVSLDUP, VMOVSHDUP,
    VMOVDDUP, VLDDQU,
    
    // derived from SSE4_1 and SSE4_2
    VDPPS, VDPPD,
    
    VPTEST,
    
    VPEXTRB, VPEXTRW, VPEXTRD, VPEXTRQ,
    VPINSRB, VPINSRD, VPINSRQ, VPMAXSB,
    VPMAXSD, VPMAXUW, VPMINSB, VPMINSD,
    VPMINUW, VPMULDQ, VPMULLD, VPMAXUB,
    VPMINUB,
    
    VBLENDPS, VBLENDPD, VPBLENDW, VPCMPEQQ,
    VROUNDPD, VROUNDPS, VROUNDSD, VROUNDSS,
    VMPSADBW, VPCMPGTQ,
    
    VBLENDVPS, VBLENDVPD, VPBLENDVB, VINSERTPS,
    VPACKUSDW, VPCMPESTRI,
    VMOVNTDQA,

    VEXTRACTPS, VPCMPESTRM, VPCMPISTRI, VPCMPISTRM,
    
    VPHMINPOSUW,

    // derived from MMX
    
    // part 1
    VPOR,
    VMOVD, VMOVQ, VPAND, VPXOR,
    VPADDB, VPADDW, VPADDD, VPADDQ,
    VPSUBB, VPSUBW, VPSUBD, VPSUBQ,
    VPANDN,
    VPSLLW, VPSLLD, VPSLLQ, VPSRLW,
    VPSRLD, VPSRLQ, VPSRAW, VPSRAD,
    
    VPSUBSB, VPMULHW, VPMULLW,
    VPADDSB, VPADDSW, VPSUBSW,

    // part 2
    VPSUBUSB, VPADDUSB, VPADDUSW, VPSUBUSW,
    VPMADDWD, VPCMPEQB, VPCMPEQW, VPCMPEQD,
    VPCMPGTB, VPCMPGTW, VPCMPGTD, 

    VPACKUSWB, VPACKSSWB, VPACKSSDW,
    
    VPUNPCKLBW, VPUNPCKLWD, VPUNPCKLDQ,
    VPUNPCKHBW, VPUNPCKHWD, VPUNPCKHDQ,

    // AVX/AVX2 (and even SSE ;) ) part 2
    // part a - tests/*/avx-part2a.asm
    PAVGB, PAVGW,
    VPAVGB, VPAVGW,

    VPHADDW, VPHADDD, VPHSUBW, VPHSUBD,
    
    VZEROALL, VPALIGNR,

    VZEROUPPER,
    VINSERTF128, VEXTRACTF128, VBROADCASTSS, VBROADCASTSD,

    VBROADCASTF128,

    // part b - tests/*/avx-part2b.asm
    STMXCSR, LDMXCSR,
    
    VLDMXCSR, VSTMXCSR,
    
    VMOVMSKPS,
    
    VPERMILPD, VPERMILPS, PCLMULQDQ, 
    VPCLMULQDQ,

    VPERM2F128, VPERM2I128,

    // part c - tests/*/avx-part2c.asm
    VPINSRW, VPMAXSW, VPMINSW,
    VPSRLDQ, VPSIGND, VPSIGNB, VPSIGNW,

    VPMULUDQ, VPMULHUW,
    
    VPMULHRSW,
    // part c extended - tests/*/avx-part2c-ext.asm
    PINSRW, PMAXSW, PMINSW, VPMAXUD, PMAXUD, PMULHUW,

    // this is FMA extension, but it uses VEX, so why not?
    // /tests/*/fma-part1.asm
    VFMADD132PD, VFMADD132PS, VFMADD132SS, VFMADD132SD,
    VFMADD213PD, VFMADD213PS, VFMADD213SS, VFMADD213SD,
    VFMADD231PD, VFMADD231PS, VFMADD231SS, VFMADD231SD,
    VFMSUB132PD, VFMSUB132PS, VFMSUB132SS, VFMSUB132SD,
    VFMSUB213PD, VFMSUB213PS, VFMSUB213SS, VFMSUB213SD,
    VFMSUB231PD, VFMSUB231PS, VFMSUB231SS, VFMSUB231SD,
    // /tests/*/fma-part2.asm
    VFNMADD132PD, VFNMADD132PS, VFNMADD132SS, VFNMADD132SD,
    VFNMADD213PD, VFNMADD213PS, VFNMADD213SS, VFNMADD213SD,
    VFNMADD231PD, VFNMADD231PS, VFNMADD231SS, VFNMADD231SD,
    VFNMSUB132PD, VFNMSUB132PS, VFNMSUB132SS, VFNMSUB132SD,
    VFNMSUB213PD, VFNMSUB213PS, VFNMSUB213SS, VFNMSUB213SD,
    VFNMSUB231PD, VFNMSUB231PS, VFNMSUB231SS, VFNMSUB231SD,
    // /tests/*/fma-part3.asm
    VFMADDSUB132PD, VFMADDSUB132PS,
    VFMADDSUB213PD, VFMADDSUB213PS,
    VFMADDSUB231PD, VFMADDSUB231PS,
    VFMSUBADD132PD, VFMSUBADD132PS,
    VFMSUBADD213PD, VFMSUBADD213PS,
    VFMSUBADD231PD, VFMSUBADD231PS,

    // same but AES
    // /tests/*/aes.asm
    AESDEC, AESENC, AESIMC,
    VAESDEC, VAESENC, VAESIMC,

    AESDECLAST, AESENCLAST,
    
    VAESDECLAST, VAESENCLAST,

    AESKEYGENASSIST,
    VAESKEYGENASSIST, // 16 chars :o

    // i hate coding conversions, but i guess someone has to do them and actually test them :)
    // so here are conversions from MMX/SSE/AVX
    // /tests/*/cvt-part1.asm
    CVTPS2DQ, CVTPS2PD, CVTPS2PI, CVTPI2PD,
    CVTPI2PS, CVTPD2DQ, CVTPD2PI, CVTPD2PS,
    CVTDQ2PD, CVTDQ2PS,
    CVTSD2SI, CVTSD2SS, CVTSI2SD, 
    CVTSI2SS, CVTSS2SD, CVTSS2SI, 

    CVTTPD2DQ, CVTTPD2PI,
    CVTTPS2DQ, CVTTPS2PI, 
    CVTTSD2SI, CVTTSS2SI,

    // /tests/*/cvt-part2.asm
    VCVTPD2DQ, VCVTPD2PS,
    VCVTPS2DQ, VCVTPS2PD,
    VCVTSD2SI, VCVTSD2SS, VCVTSI2SD, VCVTSI2SS,
    VCVTSS2SD, VCVTSS2SI, VCVTDQ2PD, VCVTDQ2PS,

    VCVTTPD2DQ, VCVTTPS2DQ, VCVTTSD2SI, VCVTTSS2SI,

    // /tests/*/norm-part1X.asm
    // X = a
    BT,
    
    CLC, CMC, CWD, CDQ, CQO, DAA,
    DAS, CLD, CLI, AAA, AAD, AAM,
    AAS, ADC, BSF, BSR, BTC, BTR,
    BTS, CBW,

    // X = b
    ADCX, ADOX, ANDN, ARPL, BLSI, BLSR,
    BZHI, CWDE, CDQE, CLAC, CLTS, CLUI,
    CLWB,
    
    BEXTR, BSWAP,

    BLSMSK,
    
    // X = c
    CMPSTRB, CMPSTRD, CMPSTRQ, CMPSTRW, CMPXCHG,
    ENDBR32, ENDBR64,
    
    CLDEMOTE, CLRSSBSY,
    
    CMPXCHG8B,
    
    CMPXCHG16B,
    // /tests/*/norm-part2.asm
    ENTER, HLT, HRESET, 
    INSB, INSD, INSW, INT,
    INT3, INTO, INT1, INVD, INVLPG, INVPCID,
    IRET, IRETD, IRETQ, LAHF, LAR, LEAVE, LLDT, LMSW,
    LODSB, LODSW, LODSD, LODSQ,
    // /tests/*/norm-part3.asm
    LOOP, LOOPE, LOOPNE, LSL, LTR, LZCNT, MOVBE,
    MOVDIRI, MOVSTRB, MOVSTRW, MOVSTRD, MOVSTRQ,
    MOVZX, MULX, 
    OUTSB, OUTSD, OUTSW, 
    PEXT,
    PDEP, PREFETCHW, PREFETCH0, PREFETCH1, PREFETCH2, PREFETCHA,
    RCL, RCR, ROL, ROR,
    // /tests/*/norm-part4.asm
    RDMSR, RDPID, RDPKRU, RDPMC, RDRAND,
    RDSEED, RDSSPQ, RDSSPD, RDTSC, RDTSCP, RORX,
    RSM, RSTORSSP, SAHF, SARX, SHLX, SHRX, SBB,
    SCASB, SCASW, SCASD, SCASQ,
    SENDUIPI, SERIALIZE, SETSSBY,
    // /tests/*/setcc.asm
    SETA, SETAE, SETB, SETBE, SETC, SETE,
    SETG, SETGE, SETL, SETLE, SETNA, SETNAE,
    SETNB, SETNBE, SETNC, SETNE, SETNG, SETNL,
    SETNGE, SETNLE, SETNO, SETNP, SETNS, SETNZ, SETO,
    SETP, SETPE, SETPO, SETS, SETZ,
    // /tests/*/norm-part5.asm
    SFENCE, SHLD,
    SHRD, SMSW, STAC, STC, STD,
    STI, STOSB, STOSW, STOSD, STOSQ,
    STR, STUI, SYSENTER, SYSEXIT, SYSRET,
    TESTUI, TPAUSE, UD0, UD1, UD2, UIRET,
    UMONITOR, UMWAIT, VERR, VERW, WAIT, FWAIT,
    WBINVD, WRFSBASE, WRGSBASE, WRMSR,
    WRPKRU,
    // /tests/*/norm-part6.asm
    XABORT, XRELEASE, XACQUIRE, XADD,
    XBEGIN, XCHG, XEND, XGETBV, XLAT, XLATB, XLATB64, XRESLDTRK,
    XRSTOR, XRSTOR64, XRSTORS, XRSTORS64, XSAVE, XSAVE64, XSAVEC,
    XSAVEC64, XSAVEOPT, XSAVEOPT64, XSAVES, XSAVES64,
    XSETBV, XSUSLDTRK, XTEST,

    // /tests/*/sha.asm
    SHA1MSG1, SHA1MSG2,
    SHA1NEXTE, SHA1RNDS4,
    SHA256MSG1, SHA256MSG2,
    SHA256RNDS2,

    // not real x86-64 instructions
    
    BYTEBE, WORDBE, DWORDBE, QWORDBE,
    BYTELE, WORDLE, DWORDLE, QWORDLE,
    
    EMPTY,

    ASCII, STRING,

    // fixed instructions
    IN, OUT, LGDT, LIDT,

    LOCK, REPNE, REPNZ, REPZ, REPE, REP,

    JCXZ, JECXZ, JRCXZ,

    // AVX-512 (with AVX-10)
    VADDPH, VADDSH, VALIGND, VALIGNQ, VBCSTNEBF162PS,
    VBCSTNESH2PS, VBLENDMPD, VBLENDMPS,
    VBROADCASTF32X2,
    VBROADCASTF32X4,
    VBROADCASTF64X2,
    VBROADCASTF32X8,
    VBROADCASTF64X4,
    VCMPPH,
    VCMPSH,
    VCOMISH,
    VCOMPRESSPD,
    VCOMPRESSPS,

    // avx-ext1
    KADDB , KADDW , KADDD , KADDQ ,
    KANDB , KANDW , KANDD , KANDQ ,
    KANDNB, KANDNW, KANDND, KANDNQ,
    KMOVB , KMOVW , KMOVD , KMOVQ ,
    KNOTB , KNOTW , KNOTD , KNOTQ ,
    KORB  , KORW  , KORD  , KORQ  ,
    KXORB , KXORW , KXORD , KXORQ ,
    KTESTB, KTESTW, KTESTD, KTESTQ,
    KXNORB, KXNORW, KXNORD, KXNORQ,

    KSHIFTLB, KSHIFTLW, KSHIFTLD, KSHIFTLQ,
    KSHIFTRB, KSHIFTRW, KSHIFTRD, KSHIFTRQ,
    KORTESTB, KORTESTW, KORTESTD, KORTESTQ,
    
    KUNPCKBW, KUNPCKDQ, KUNPCKWD,
    
    // avx-ext2
    VCVTDQ2PH, VCVTNE2PS2BF16, VCVTNEEBF162PS, VCVTNEEPH2PS,
    VCVTNEOBF162PS, VCVTNEOPH2PS, VCVTNEPS2BF16, VCVTPD2PH,
    VCVTPD2QQ, VCVTPD2UDQ, VCVTPD2UQQ, VCVTPH2DQ, VCVTPH2PD,
    VCVTPH2PS, VCVTPH2PSX, VCVTPH2QQ, VCVTPH2UDQ, VCVTPH2UQQ,
    VCVTPH2UW, VCVTPH2W, VCVTPS2PH, VCVTPS2PHX, VCVTPS2QQ,
    VCVTPS2UDQ, VCVTPS2UQQ, VCVTQQ2PD, VCVTQQ2PH, VCVTQQ2PS,
    VCVTSD2SH, VCVTSD2USI, VCVTSH2SD, VCVTSH2SI, VCVTSH2SS,
    
    // avx-ext3
    VCVTSH2USI, VCVTSI2SH, VCVTSS2SH, VCVTSS2USI, VCVTTPD2QQ,
    VCVTTPD2UDQ, VCVTTPD2UQQ, VCVTTPH2DQ, VCVTTPH2QQ, VCVTTPH2UDQ,
    VCVTTPH2UQQ, VCVTTPH2UW, VCVTTPH2W, VCVTTPS2QQ, VCVTTPS2UDQ,
    VCVTTPS2UQQ,VCVTTSD2USI, VCVTTSH2SI, VCVTTSH2USI, VCVTTSS2USI,
    VCVTUDQ2PD, VCVTUDQ2PH, VCVTUDQ2PS, VCVTUQQ2PD, VCVTUQQ2PH,
    VCVTUQQ2PS, VCVTUSI2SD, VCVTUSI2SH, VCVTUSI2SS, VCVTUW2PH,
    VCVTW2PH,
    
    // avx-ext4
    VDBPSADBW, VDIVPH, VDIVSH, VDPBF16PS, VEXPANDPD, VEXPANDPS,
    VEXTRACTF32X4, VEXTRACTF64X2, VEXTRACTF32X8, VEXTRACTF64X4,
    VEXTRACTI128, VEXTRACTI32X4, VEXTRACTI64X2, VEXTRACTI32X8,
    VEXTRACTI64X4, VFCMADDCPH, VFMADDCPH, VFMADDCSH, VFCMADDCSH, VFCMULCPH,
    VFCMULCSH, VFMULCPH, VFMULCSH, VFIXUPIMMPD, VFIXUPIMMPS, VFIXUPIMMSD,
    VFIXUPIMMSS,

    // avx-ext5
    VFMADD132PH, VFMADD213PH, VFMADD231PH,
    VFNMADD132PH, VFNMADD213PH, VFNMADD231PH,
    VFMADD132SH, VFMADD213SH, VFMADD231SH,
    VFNMADD132SH, VFNMADD213SH, VFNMADD231SH,
    VFMADDSUB132PH, VFMADDSUB213PH, VFMADDSUB231PH,
    VFMSUB132PH, VFMSUB213PH, VFMSUB231PH,
    VFNMSUB132PH, VFNMSUB213PH, VFNMSUB231PH,
    VFMSUB132SH, VFMSUB213SH, VFMSUB231SH,
    VFNMSUB132SH, VFNMSUB213SH, VFNMSUB231SH,
    VFMSUBADD132PH, VFMSUBADD213PH, VFMSUBADD231PH,

    // avx-ext6
    VFPCLASSPD, VFPCLASSPH, VFPCLASSPS, VFPCLASSSD,
    VFPCLASSSH, VFPCLASSSS, VGETEXPPD, VGETEXPPH,
    VGETEXPPS, VGETEXPSD, VGETEXPSH, VGETEXPSS, VGETMANTPD,
    VGETMANTPH, VGETMANTPS, VGETMANTSD, VGETMANTSH,
    VGETMANTSS, VINSERTF32X4, VINSERTF64X2, VINSERTF32X8,
    VINSERTF64X4, VINSERTI32X4, VINSERTI64X2, VINSERTI32X8,
    VINSERTI64X4, VINSERTI128, VMASKMOVPS, VMASKMOVPD,

    // avx-ext7
    VMAXPH, VMAXSH, VMINPH, VMINSH, VMOVSH, VMOVW,
    VMULPH, VMULSH, VP2INTERSECTD, VP2INTERSECTQ,
    VPBLENDD, VPBLENDMB, VPBLENDMW, VPBLENDMD,
    VPBLENDMQ, VPBROADCASTB, VPBROADCASTW,
    VPBROADCASTD, VPBROADCASTQ, VPBROADCASTI32X2,
    VPBROADCASTI128, VPBROADCASTI32X4, VPBROADCASTI64X2,
    VPBROADCASTI32X8, VPBROADCASTMB2Q, VPBROADCASTI64X4,
    VPBROADCASTMW2D, VPCMPB, VPCMPUB, VPCMPD,
    VPCMPUD, VPCMPQ, VPCMPUQ, VPCMPW, VPCMPUW,
    VPCOMPRESSB, VPCOMPRESSW, VPCOMPRESSD, VPCOMPRESSQ,
    
    // avx-ext8
    VPCONFLICTD, VPCONFLICTQ, VPDPBSSD, VPDPBSSDS,
    VPDPBSUD, VPDPBSUDS, VPDPBUUD, VPDPBUSD, VPDPBUSDS,
    VPDPWSSD, VPDPWSSDS, VPDPWSUD, VPDPWSUDS, VPDPWUSD, VPDPBUUDS, VPDPWUUDS,
    VPDPWUSDS, VPDPWUUD, VPERMB, VPERMD, VPERMW, VPERMI2B,
    VPERMI2W, VPERMI2D, VPERMI2Q, VPERMI2PS, VPERMPD, VPERMI2PD,
    VPERMPS, VPERMQ, VPERMT2B, VPERMT2W, VPERMT2D, VPERMT2Q,
    VPERMT2PS, VPERMT2PD,VPEXPANDB, VPEXPANDW, VPEXPANDD,
    VPEXPANDQ, VPLZCNTD, VPLZCNTQ, VPMADD52HUQ, VPMADD52LUQ,

    // avx-ext9
    VPMASKMOVD, VPMASKMOVQ, VPMOVB2M, VPMOVW2M, VPMOVD2M,
    VPMOVQ2M, VPMOVDB, VPMOVSDB, VPMOVUSDB, VPMOVDW, VPMOVSDW,
    VPMOVUSDW, VPMOVM2B, VPMOVM2W, VPMOVM2D, VPMOVM2Q, VPMOVQB,
    VPMOVSQB, VPMOVUSQB, VPMOVQD, VPMOVSQD, VPMOVUSQD, VPMOVQW,
    VPMOVSQW, VPMOVUSQW, VPMOVWB, VPMOVSWB, VPMOVUSWB,

    // avx-exta
    VPMULTISHIFTQB, VPOPCNTB, VPOPCNTW, VPOPCNTD, VPOPCNTQ,VPROLVD, VPROLVQ,
    VPROLD, VPROLQ, VPRORD, VPRORVD, VPRORQ, VPRORVQ,
    VPSHLDW, VPSHLDD, VPSHLDQ, VPSHLDVW, VPSHLDVD, VPSHLDVQ,
    VPSHRDW, VPSHRDD, VPSHRDQ, VPSHRDVW, VPSHRDVD, VPSHRDVQ,
    VPSHUFBITQMB, VPSLLVW, VPSLLVD, VPSLLVQ,
    VPSRAVW, VPSRAVD, VPSRAVQ, VPSRLVW, VPSRLVD, VPSRLVQ, VPTERNLOGD,
    VPTERNLOGQ, VPTESTMB, VPTESTMW, VPTESTMD, VPTESTMQ,VPTESTNMB,
    VPTESTNMW, VPTESTNMD, VPTESTNMQ, VRANGEPD, VRANGEPS,VRANGESD, VRANGESS, 

    // avx-extb
    VRCP14PD, VRCP14PS, VRCP14SD, VRCP14SS, VRCPPH, VRCPSH,
    VREDUCEPD, VREDUCEPH, VREDUCEPS, VREDUCESD, VREDUCESH, VREDUCESS,
    VRNDSCALEPD, VRNDSCALEPH, VRNDSCALEPS, VRNDSCALESD, VRNDSCALESH,
    VRNDSCALESS, VRSQRT14PD, VRSQRT14PS, VRSQRT14SD, VRSQRT14SS, VRSQRTPH,
    VRSQRTSH, VSCALEFPD, VSCALEFPH, VSCALEFPS, VSCALEFSD, VSCALEFSH, VSCALEFSS,
    
    // avx-extc
    VSHA512MSG1, VSHA512MSG2, VSHA512RNDS2, VSHUFF32X4,
    VSHUFF64X2, VSHUFI32X4, VSHUFI64X2,
    VSM3MSG1, VSM3MSG2, VSM3RNDS2, VSM4KEY4,
    VSM4RNDS4, VSQRTPH, VSQRTSH, VSUBPH, VSUBSH,
    VTESTPD, VTESTPS, VUCOMISH,

    // avx-extd
    PREFETCHWT1, V4FMADDPS, V4FNMADDPS, V4FMADDSS, V4FNMADDSS,
    VEXP2PD, VEXP2PS, VP4DPWSSD, VP4DPWSSDS, VRCP28PD, VRCP28SD,
    VRCP28PS, VRCP28SS, VRSQRT28PD, VRSQRT28SD, VRSQRT28PS, VRSQRT28SS,

    // avx-exte - vsib
    VGATHERQPD, VGATHERDPS, VGATHERDPD,
    VGATHERQPS, VPGATHERDD, VPGATHERDQ,
    VPGATHERQQ, VPGATHERQD, VPSCATTERDD,
    VPSCATTERDQ, VPSCATTERQD, VPSCATTERQQ,
    VSCATTERDPS, VSCATTERDPD, VSCATTERQPS,
    VSCATTERQPD, VGATHERPF0DPS, VGATHERPF0QPS,
    VGATHERPF0DPD, VGATHERPF0QPD, VGATHERPF1DPS,
    VGATHERPF1QPS, VGATHERPF1DPD, VGATHERPF1QPD,
    VSCATTERPF0DPS, VSCATTERPF0QPS, VSCATTERPF0DPD,
    VSCATTERPF0QPD, VSCATTERPF1DPS, VSCATTERPF1QPS,
    VSCATTERPF1DPD, VSCATTERPF1QPD,

    // Intel APX

    // intel-apx0
    AAADD, AAAND, AADC, AADCX, AADD, AADOX, AAND, AANDN,
    AAOR, AAXOR, ABEXTR, ABLSI, ABLSMSK, ABLSR, ABZHI,

    ACMOVA, ACMOVB, ACMOVC, ACMOVE, ACMOVG,
    ACMOVL, ACMOVO, ACMOVP, ACMOVS, ACMOVZ,

    ACMOVAE, ACMOVBE, ACMOVGE, ACMOVLE, ACMOVNA,
    ACMOVNB, ACMOVNC, ACMOVNE, ACMOVNG, ACMOVNL,
    ACMOVNO, ACMOVNP, ACMOVNS, ACMOVNZ, ACMOVPE, ACMOVPO,
    
    ACMOVNBE, ACMOVNAE, ACMOVNGE,ACMOVNLE,

    ACRC32, ADEC, ADIV, AIDIV,
    AIMUL, AIMULZU, AINC, AINVEPT, AINVPCID, AINVVPID,
    AKMOVB, AKMOVD, AKMOVQ, AKMOVW, ALZCNT,
    AMOVBE, AMOVDIRI, AMOVRS, AMUL, AMULX,
    ANEG, ANOT, AOR, APDEP, APEXT, APOPCNT,

    ARCL, ARCR, ARDMSR, AROL, AROR, ARORX, ASAR, ASARX,
    ASBB, ASHL, ASHR, ASHRD, ASHRX, ASHLD, ASHLX,
    ASUB, ATZCNT, AXOR,

    JMPABS,

    // intel-apx1
    CCMPB, CCMPBE, CCMPF, CCMPL, CCMPLE,
    CCMPNB, CCMPZ, CCMPNBE, CCMPNL, CCMPNLE,
    CCMPNO, CCMPNS, CCMPNZ, CCMPO, CCMPS, CCMPT,
        // pasm's added mnemonics
        CCMPNA, CCMPA, CCMPNAE, CCMPAE, CCMPE, CCMPNE,
        CCMPGE, CCMPG, CCMPNG, CCMPNGE, CCMPC, CCMPNC,

    CTESTB, CTESTBE, CTESTF, CTESTL, CTESTLE,
    CTESTNB, CTESTZ, CTESTNBE, CTESTNL, CTESTNLE,
    CTESTNO, CTESTNS, CTESTNZ, CTESTO, CTESTS, CTESTT,
        // pasm's added mnemonics
        CTESTNA, CTESTA, CTESTNAE, CTESTAE, CTESTE, CTESTNE,
        CTESTGE, CTESTG, CTESTNG, CTESTNGE, CTESTC, CTESTNC,
    
    // intel-apx2
    CFCMOVA, CFCMOVB, CFCMOVE, CFCMOVG,
    CFCMOVL, CFCMOVO, CFCMOVP, CFCMOVS, CFCMOVZ,

    CFCMOVAE, CFCMOVBE, CFCMOVGE, CFCMOVLE, CFCMOVNA,
    CFCMOVNB, CFCMOVNE, CFCMOVNG, CFCMOVNL,
    CFCMOVNO, CFCMOVNP, CFCMOVNS, CFCMOVNZ, CFCMOVPE, CFCMOVPO,
   
    CFCMOVNC, CFCMOVC,
    CFCMOVNBE, CFCMOVNAE, CFCMOVNGE,CFCMOVNLE,
    
    // intel-apx3
    SETAZU, SETAEZU, SETBZU, SETBEZU, SETCZU, SETEZU,
    SETGZU, SETGEZU, SETLZU, SETLEZU, SETNAZU, SETNAEZU,
    SETNBZU, SETNBEZU, SETNCZU, SETNEZU, SETNGZU, SETNLZU,
    SETNGEZU, SETNLEZU, SETNOZU, SETNPZU, SETNSZU, SETNZZU, SETOZU,
    SETPZU, SETPEZU, SETPOZU, SETSZU, SETZZU,
    
    // intel-apx4
    POP2, POP2P, POPP, PUSH2, PUSH2P, PUSHP,

    // CET_SS (Shadow Stack)
    INCSSPD, INCSSPQ, SAVEPREVSSP, WRSSD, WRSSQ,
    WRUSSD, WRUSSQ,
    // APX extended
    AWRSSD, AWRSSQ,
    AWRUSSD, AWRUSSQ,

    // missing support
    RDFSBASE, RDGSBASE, MOVDIR64B, WBNOINVD,
    PREFETCHIT0, PREFETCHIT1, PTWRITE, PCONFIG, 
    ENQCMD, ENQCMDS,
    AENQCMDS, AENQCMD, RDMSRLIST, WRMSRLIST,
    PBNDKB, POPAW, POPAD, POPAQ,
    PUSHAW, PUSHAD, PUSHAQ, SGDT, SIDT,
    SLDT, MOVSX, MOVSXD, LFS, LGS,
    NOPL, SWAPGS,

    // AMD-V
    INVLPGA, VMRUN, VMLOAD, VMSAVE, STGI, CLGI, VMMCALL, SKINIT, VMGEXIT,
    PSMASH, RMPUPDATE, PVALIDATE, RMPADJUST, RMPQUERY, RMPREAD,

    // Intel VT-x
    VMXON, VMXOFF, VMPTRLD, VMPTRST, VMCLEAR, VMLAUNCH, VMRESUME, VMREAD,
    VMWRITE, VMCALL, INVEPT, INVVPID, VMFUNC, SEAMOPS, SEAMRET, SEAMCALL,
    TDCALL,

    // SMX
    GETSEC,
    
    // x87
    // part 0
    FNINIT, FLDCW, FNSTCW, FNSTSW, FNCLEX, FLDENV, FNSTENV, FNSAVE, FRSTOR,
    FNENI, FNDISI, FINIT, FSTCW, FSTSW, FCLEX, FSTENV, FSAVE, FENI, FDISI,

    // part 1
    FLD, FST, FSTP, FLDZ, FLD1, FLDPI, FLDL2T, FLDL2E, FLDLG2, FLDLN2,
    FXCH, FILD, FIST, FISTP, FBLD, FBSTP,

    // part 2
    FADD, FMUL, FSUB, FSUBR, FDIV, FDIVR, FCOM, FADDP, FMULP, FSUBP, FSUBRP,
    FDIVP, FDIVRP, FCOMP, FCOMPP,

    // part 3
    FIADD, FIMUL, FISUB, FIDIV, FIDIVR, FICOM, FICOMP, FCHS, FABS, FTST, FXAM,
    FXTRACT, FPREM, FSQRT, FRNDINT, FSCALE, F2XM1, FYL2X, FPTAN, FPATAN,
    FYL2XP1, FISUBR,

    // part 4
    FNOP, FDECSTP, FINCSTP, FFREE, FNSETPM, FNSTSWAX, FSTSWAX,
    FUCOM, FUCOMP, FUCOMPP, FPREM1, FSINCOS, FSIN, FCOS,
    FSETPM,

    // part 5
    FCMOVB, FCMOVE, FCMOVBE, FCMOVU, FCMOVNB, FCMOVNE, FCMOVNBE, FCMOVNU,
    FCOMI, FCOMIP, FUCOMI, FUCOMIP, FXSAVE, FXRSTOR, FISTTP,FXSAVE64, FXRSTOR64,

    // SHA
    LOADIWKEY, ENCODEKEY128, ENCODEKEY256, AESENC128KL, AESDEC128KL,
    AESENC256KL, AESDEC256KL, AESENCWIDE128KL, AESDECWIDE128KL, AESENCWIDE256KL,
    AESDECWIDE256KL,
    
    // CMPccXADD
    CMPBXADD, CMPBEXADD, CMPLXADD, CMPLEXADD,
    CMPNBXADD, CMPZXADD, CMPNBEXADD, CMPNLXADD, CMPNLEXADD,
    CMPNOXADD, CMPNSXADD, CMPNZXADD, CMPOXADD, CMPSXADD,
        // pasm's added mnemonics
        CMPNAXADD, CMPAXADD, CMPNAEXADD, CMPAEXADD, CMPEXADD, CMPNEXADD,
        CMPGEXADD, CMPGXADD, CMPNGXADD, CMPNGEXADD, CMPCXADD, CMPNCXADD,
    // APX extension
    ACMPBXADD, ACMPBEXADD, ACMPLXADD, ACMPLEXADD,
    ACMPNBXADD, ACMPZXADD, ACMPNBEXADD, ACMPNLXADD, ACMPNLEXADD,
    ACMPNOXADD, ACMPNSXADD, ACMPNZXADD, ACMPOXADD, ACMPSXADD,
        // pasm's added mnemonics
        ACMPNAXADD, ACMPAXADD, ACMPNAEXADD, ACMPAEXADD, ACMPEXADD, ACMPNEXADD,
        ACMPGEXADD, ACMPGXADD, ACMPNGXADD, ACMPNGEXADD, ACMPCXADD, ACMPNCXADD,

    // SGX
    ENCLS, ENCLU, ENCLV,

    // long jump
    LJMP, LCALL,

    PMOVSXBW, PMOVSXBD, PMOVSXBQ, PMOVSXWD, PMOVSXWQ, PMOVSXDQ,
    VPMOVSXBW, VPMOVSXBD, VPMOVSXBQ, VPMOVSXWD, VPMOVSXWQ, VPMOVSXDQ,
    
    PMOVZXBW, PMOVZXBD, PMOVZXBQ, PMOVZXWD, PMOVZXWQ, PMOVZXDQ,
    VPMOVZXBW, VPMOVZXBD, VPMOVZXBQ, VPMOVZXWD, VPMOVZXWQ, VPMOVZXDQ,

    // this has no real purpose, but why not?
    __LAST
}

#[cfg(not(feature = "refresh"))]
impl FromStr for Mnemonic {
    type Err = ();
    fn from_str(str_ins: &str) -> Result<Self, <Self as FromStr>::Err> {
        if let Some(m) = ins_switch::mnem_fromstr(str_ins) {
            Ok(m)
        } else {
            Err(())
        }
    }
}

impl Mnemonic {
    pub fn allows_diff_size(&self, left: Option<Size>, right: Option<Size>) -> bool {
        if matches!(&self, Self::LAR) {
            let l = left.unwrap();
            let r = right.unwrap();
            l == Size::Word && r == Size::Dword
        } else if matches!(
            &self,
            Self::SHL
                | Self::SHR
                | Self::SAL
                | Self::SAR
                | Self::ROL
                | Self::ROR
                | Self::RCL
                | Self::RCR
        ) {
            let r = right.unwrap();
            r == Size::Byte
        } else {
            false
        }
    }
    pub fn allows_mem_mem(&self) -> bool {
        false
    }
    #[rustfmt::skip]
    pub fn defaults_to_64bit(&self) -> bool {
        matches!(
            self,
            Self::PUSH     | Self::POP     | Self::PADDB |
            Self::PADDW    | Self::PADDD   | Self::PADDQ |
            Self::PINSRD   | Self::CVTPD2PI| Self::CVTTPD2PI|
            Self::CVTTPS2PI| Self::CVTPI2PS| Self::CVTPS2PI|
            Self::CVTPS2DQ | Self::CVTSS2SD| Self::CVTPI2PD|
            Self::CVTPS2PD
        )
    }
}

#[cfg(feature = "iinfo")]
impl ToString for Mnemonic {
    fn to_string(&self) -> String {
        format!("{:?}", self).to_lowercase()
    }
}
