// rasmx86_64 - src/shr/ins_switch.rs
// ----------------------------------
// made by matissoss
// licensed under MPL 2.0
//
// WARNING: THIS CODE WAS GENERATED BY ins_adder MODULE

use crate::shr::ins::Mnemonic as Ins;

pub fn mnem_fromstr(str: &str) -> Option<Ins> {
	let rstr = str.as_bytes();
	match rstr.len() {
		2 => match rstr[0] {b'b' => match rstr[1] {b't' => Some(Ins::BT),
_=>None}
b'i' => match rstr[1] {b'n' => Some(Ins::IN),
_=>None}
b'o' => match rstr[1] {b'r' => Some(Ins::OR),
_=>None}
b'j' => match rstr[1]{b'a' => Some(Ins::JA),
b'b' => Some(Ins::JB),
b'c' => Some(Ins::JC),
b'e' => Some(Ins::JE),
b'g' => Some(Ins::JG),
b'l' => Some(Ins::JL),
b'o' => Some(Ins::JO),
b'p' => Some(Ins::JP),
b's' => Some(Ins::JS),
b'z' => Some(Ins::JZ),
_=>None}
_=>None}3 => match rstr[0] {b'h' => match rstr[1] {b'l' => match rstr[2] {b't' => Some(Ins::HLT),
_=>None}
_=>None}
b'i' => match rstr[1] {b'n' => match rstr[2]{b'c' => Some(Ins::INC),
b's' => Some(Ins::INS),
b't' => Some(Ins::INT),
_=>None}
_=>None}
b'o' => match rstr[1] {b'u' => match rstr[2] {b't' => Some(Ins::OUT),
_=>None}
_=>None}
b'p' => match rstr[1] {b'o' => match rstr[2]{b'p' => Some(Ins::POP),
b'r' => Some(Ins::POR),
_=>None}
_=>None}
b'u' => match rstr[1] {b'd' => match rstr[2]{b'0' => Some(Ins::UD0),
b'1' => Some(Ins::UD1),
b'2' => Some(Ins::UD2),
_=>None}
_=>None}
b'x' => match rstr[1] {b'o' => match rstr[2] {b'r' => Some(Ins::XOR),
_=>None}
_=>None}
b'a' => match rstr[1]{b'n' => match rstr[2] {b'd' => Some(Ins::AND),
_=>None}
b'a' => match rstr[2]{b'a' => Some(Ins::AAA),
b'd' => Some(Ins::AAD),
b'm' => Some(Ins::AAM),
b's' => Some(Ins::AAS),
_=>None}
b'd' => match rstr[2]{b'c' => Some(Ins::ADC),
b'd' => Some(Ins::ADD),
_=>None}
_=>None}
b'b' => match rstr[1]{b's' => match rstr[2]{b'f' => Some(Ins::BSF),
b'r' => Some(Ins::BSR),
_=>None}
b't' => match rstr[2]{b'c' => Some(Ins::BTC),
b'r' => Some(Ins::BTR),
b's' => Some(Ins::BTS),
_=>None}
_=>None}
b'c' => match rstr[1]{b'b' => match rstr[2] {b'w' => Some(Ins::CBW),
_=>None}
b'd' => match rstr[2] {b'q' => Some(Ins::CDQ),
_=>None}
b'q' => match rstr[2] {b'o' => Some(Ins::CQO),
_=>None}
b'w' => match rstr[2] {b'd' => Some(Ins::CWD),
_=>None}
b'l' => match rstr[2]{b'c' => Some(Ins::CLC),
b'd' => Some(Ins::CLD),
b'i' => Some(Ins::CLI),
_=>None}
b'm' => match rstr[2]{b'c' => Some(Ins::CMC),
b'p' => Some(Ins::CMP),
_=>None}
_=>None}
b'd' => match rstr[1]{b'e' => match rstr[2] {b'c' => Some(Ins::DEC),
_=>None}
b'i' => match rstr[2] {b'v' => Some(Ins::DIV),
_=>None}
b'a' => match rstr[2]{b'a' => Some(Ins::DAA),
b's' => Some(Ins::DAS),
_=>None}
_=>None}
b'j' => match rstr[1]{b'a' => match rstr[2] {b'e' => Some(Ins::JAE),
_=>None}
b'b' => match rstr[2] {b'e' => Some(Ins::JBE),
_=>None}
b'g' => match rstr[2] {b'e' => Some(Ins::JGE),
_=>None}
b'l' => match rstr[2] {b'e' => Some(Ins::JLE),
_=>None}
b'm' => match rstr[2] {b'p' => Some(Ins::JMP),
_=>None}
b'n' => match rstr[2]{b'a' => Some(Ins::JNA),
b'b' => Some(Ins::JNB),
b'c' => Some(Ins::JNC),
b'e' => Some(Ins::JNE),
b'g' => Some(Ins::JNG),
b'l' => Some(Ins::JNL),
b'o' => Some(Ins::JNO),
b'p' => Some(Ins::JNP),
b's' => Some(Ins::JNS),
b'z' => Some(Ins::JNZ),
_=>None}
b'p' => match rstr[2]{b'e' => Some(Ins::JPE),
b'o' => Some(Ins::JPO),
_=>None}
_=>None}
b'l' => match rstr[1]{b'a' => match rstr[2] {b'r' => Some(Ins::LAR),
_=>None}
b'd' => match rstr[2] {b's' => Some(Ins::LDS),
_=>None}
b'f' => match rstr[2] {b's' => Some(Ins::LFS),
_=>None}
b'g' => match rstr[2] {b's' => Some(Ins::LGS),
_=>None}
b't' => match rstr[2] {b'r' => Some(Ins::LTR),
_=>None}
b'e' => match rstr[2]{b'a' => Some(Ins::LEA),
b's' => Some(Ins::LES),
_=>None}
b's' => match rstr[2]{b'l' => Some(Ins::LSL),
b's' => Some(Ins::LSS),
_=>None}
_=>None}
b'm' => match rstr[1]{b'o' => match rstr[2] {b'v' => Some(Ins::MOV),
_=>None}
b'u' => match rstr[2] {b'l' => Some(Ins::MUL),
_=>None}
_=>None}
b'n' => match rstr[1]{b'e' => match rstr[2] {b'g' => Some(Ins::NEG),
_=>None}
b'o' => match rstr[2]{b'p' => Some(Ins::NOP),
b't' => Some(Ins::NOT),
_=>None}
_=>None}
b'r' => match rstr[1]{b'e' => match rstr[2] {b't' => Some(Ins::RET),
_=>None}
b's' => match rstr[2] {b'm' => Some(Ins::RSM),
_=>None}
b'c' => match rstr[2]{b'l' => Some(Ins::RCL),
b'r' => Some(Ins::RCR),
_=>None}
b'o' => match rstr[2]{b'l' => Some(Ins::ROL),
b'r' => Some(Ins::ROR),
_=>None}
_=>None}
b's' => match rstr[1]{b'b' => match rstr[2] {b'b' => Some(Ins::SBB),
_=>None}
b'u' => match rstr[2] {b'b' => Some(Ins::SUB),
_=>None}
b'a' => match rstr[2]{b'l' => Some(Ins::SAL),
b'r' => Some(Ins::SAR),
_=>None}
b'h' => match rstr[2]{b'l' => Some(Ins::SHL),
b'r' => Some(Ins::SHR),
_=>None}
b't' => match rstr[2]{b'c' => Some(Ins::STC),
b'd' => Some(Ins::STD),
b'i' => Some(Ins::STI),
b'r' => Some(Ins::STR),
_=>None}
_=>None}
_=>None}4 => match rstr[0] {b'd' => match rstr[1] {b'p' => match rstr[2] {b'p' => match rstr[3]{b'd' => Some(Ins::DPPD),
b's' => Some(Ins::DPPS),
_=>None}
_=>None}
_=>None}
b'e' => match rstr[1] {b'm' => match rstr[2] {b'm' => match rstr[3] {b's' => Some(Ins::EMMS),
_=>None}
_=>None}
_=>None}
b'j' => match rstr[1] {b'n' => match rstr[2]{b'a' => match rstr[3] {b'e' => Some(Ins::JNAE),
_=>None}
b'b' => match rstr[3] {b'e' => Some(Ins::JNBE),
_=>None}
b'g' => match rstr[3] {b'e' => Some(Ins::JNGE),
_=>None}
b'l' => match rstr[3] {b'e' => Some(Ins::JNLE),
_=>None}
_=>None}
_=>None}
b'r' => match rstr[1] {b'o' => match rstr[2] {b'r' => match rstr[3] {b'x' => Some(Ins::RORX),
_=>None}
_=>None}
_=>None}
b't' => match rstr[1] {b'e' => match rstr[2] {b's' => match rstr[3] {b't' => Some(Ins::TEST),
_=>None}
_=>None}
_=>None}
b'w' => match rstr[1] {b'a' => match rstr[2] {b'i' => match rstr[3] {b't' => Some(Ins::WAIT),
_=>None}
_=>None}
_=>None}
b'a' => match rstr[1]{b'n' => match rstr[2] {b'd' => match rstr[3] {b'n' => Some(Ins::ANDN),
_=>None}
_=>None}
b'r' => match rstr[2] {b'p' => match rstr[3] {b'l' => Some(Ins::ARPL),
_=>None}
_=>None}
b'd' => match rstr[2]{b'c' => match rstr[3] {b'x' => Some(Ins::ADCX),
_=>None}
b'o' => match rstr[3] {b'x' => Some(Ins::ADOX),
_=>None}
_=>None}
_=>None}
b'b' => match rstr[1]{b'l' => match rstr[2] {b's' => match rstr[3]{b'i' => Some(Ins::BLSI),
b'r' => Some(Ins::BLSR),
_=>None}
_=>None}
b'z' => match rstr[2] {b'h' => match rstr[3] {b'i' => Some(Ins::BZHI),
_=>None}
_=>None}
_=>None}
b'c' => match rstr[1]{b'a' => match rstr[2] {b'l' => match rstr[3] {b'l' => Some(Ins::CALL),
_=>None}
_=>None}
b'q' => match rstr[2] {b'd' => match rstr[3] {b'e' => Some(Ins::CQDE),
_=>None}
_=>None}
b'w' => match rstr[2] {b'd' => match rstr[3] {b'e' => Some(Ins::CWDE),
_=>None}
_=>None}
b'l' => match rstr[2]{b'a' => match rstr[3] {b'c' => Some(Ins::CLAC),
_=>None}
b't' => match rstr[3] {b's' => Some(Ins::CLTS),
_=>None}
b'u' => match rstr[3] {b'i' => Some(Ins::CLUI),
_=>None}
b'w' => match rstr[3] {b'b' => Some(Ins::CLWB),
_=>None}
_=>None}
_=>None}
b'i' => match rstr[1]{b'd' => match rstr[2] {b'i' => match rstr[3] {b'v' => Some(Ins::IDIV),
_=>None}
_=>None}
b'm' => match rstr[2] {b'u' => match rstr[3] {b'l' => Some(Ins::IMUL),
_=>None}
_=>None}
b'r' => match rstr[2] {b'e' => match rstr[3] {b't' => Some(Ins::IRET),
_=>None}
_=>None}
b'n' => match rstr[2]{b'v' => match rstr[3] {b'd' => Some(Ins::INVD),
_=>None}
b's' => match rstr[3]{b'd' => Some(Ins::INSD),
b'w' => Some(Ins::INSW),
_=>None}
b't' => match rstr[3]{b'1' => Some(Ins::INT1),
b'3' => Some(Ins::INT3),
b'o' => Some(Ins::INTO),
_=>None}
_=>None}
_=>None}
b'l' => match rstr[1]{b'a' => match rstr[2] {b'h' => match rstr[3] {b'f' => Some(Ins::LAHF),
_=>None}
_=>None}
b'l' => match rstr[2] {b'd' => match rstr[3] {b't' => Some(Ins::LLDT),
_=>None}
_=>None}
b'm' => match rstr[2] {b's' => match rstr[3] {b'w' => Some(Ins::LMSW),
_=>None}
_=>None}
b'o' => match rstr[2]{b'd' => match rstr[3] {b's' => Some(Ins::LODS),
_=>None}
b'o' => match rstr[3] {b'p' => Some(Ins::LOOP),
_=>None}
_=>None}
_=>None}
b'm' => match rstr[1]{b'o' => match rstr[2] {b'v' => match rstr[3]{b'd' => Some(Ins::MOVD),
b'q' => Some(Ins::MOVQ),
_=>None}
_=>None}
b'u' => match rstr[2] {b'l' => match rstr[3] {b'x' => Some(Ins::MULX),
_=>None}
_=>None}
_=>None}
b'o' => match rstr[1]{b'r' => match rstr[2] {b'p' => match rstr[3]{b'd' => Some(Ins::ORPD),
b's' => Some(Ins::ORPS),
_=>None}
_=>None}
b'u' => match rstr[2] {b't' => match rstr[3] {b's' => Some(Ins::OUTS),
_=>None}
_=>None}
_=>None}
b'p' => match rstr[1]{b'a' => match rstr[2] {b'n' => match rstr[3] {b'd' => Some(Ins::PAND),
_=>None}
_=>None}
b'd' => match rstr[2] {b'e' => match rstr[3] {b'p' => Some(Ins::PDEP),
_=>None}
_=>None}
b'e' => match rstr[2] {b'x' => match rstr[3] {b't' => Some(Ins::PEXT),
_=>None}
_=>None}
b'o' => match rstr[2] {b'p' => match rstr[3] {b'f' => Some(Ins::POPF),
_=>None}
_=>None}
b'u' => match rstr[2] {b's' => match rstr[3] {b'h' => Some(Ins::PUSH),
_=>None}
_=>None}
b'x' => match rstr[2] {b'o' => match rstr[3] {b'r' => Some(Ins::PXOR),
_=>None}
_=>None}
_=>None}
b's' => match rstr[1]{b'c' => match rstr[2] {b'a' => match rstr[3] {b's' => Some(Ins::SCAS),
_=>None}
_=>None}
b'e' => match rstr[2] {b't' => match rstr[3]{b'a' => Some(Ins::SETA),
b'b' => Some(Ins::SETB),
b'c' => Some(Ins::SETC),
b'e' => Some(Ins::SETE),
b'g' => Some(Ins::SETG),
b'l' => Some(Ins::SETL),
b'o' => Some(Ins::SETO),
b'p' => Some(Ins::SETP),
b's' => Some(Ins::SETS),
b'z' => Some(Ins::SETZ),
_=>None}
_=>None}
b'g' => match rstr[2] {b'd' => match rstr[3] {b't' => Some(Ins::SGDT),
_=>None}
_=>None}
b'i' => match rstr[2] {b'd' => match rstr[3] {b't' => Some(Ins::SIDT),
_=>None}
_=>None}
b'l' => match rstr[2] {b'd' => match rstr[3] {b't' => Some(Ins::SLDT),
_=>None}
_=>None}
b'm' => match rstr[2] {b's' => match rstr[3] {b'w' => Some(Ins::SMSW),
_=>None}
_=>None}
b'a' => match rstr[2]{b'h' => match rstr[3] {b'f' => Some(Ins::SAHF),
_=>None}
b'r' => match rstr[3] {b'x' => Some(Ins::SARX),
_=>None}
_=>None}
b'h' => match rstr[2]{b'l' => match rstr[3]{b'd' => Some(Ins::SHLD),
b'x' => Some(Ins::SHLX),
_=>None}
b'r' => match rstr[3]{b'd' => Some(Ins::SHRD),
b'x' => Some(Ins::SHRX),
_=>None}
_=>None}
b't' => match rstr[2]{b'a' => match rstr[3] {b'c' => Some(Ins::STAC),
_=>None}
b'o' => match rstr[3] {b's' => Some(Ins::STOS),
_=>None}
b'u' => match rstr[3] {b'i' => Some(Ins::STUI),
_=>None}
_=>None}
_=>None}
b'v' => match rstr[1]{b'e' => match rstr[2] {b'r' => match rstr[3]{b'r' => Some(Ins::VERR),
b'w' => Some(Ins::VERW),
_=>None}
_=>None}
b'p' => match rstr[2] {b'o' => match rstr[3] {b'r' => Some(Ins::VPOR),
_=>None}
_=>None}
_=>None}
b'x' => match rstr[1]{b'a' => match rstr[2] {b'd' => match rstr[3] {b'd' => Some(Ins::XADD),
_=>None}
_=>None}
b'c' => match rstr[2] {b'h' => match rstr[3] {b'g' => Some(Ins::XCHG),
_=>None}
_=>None}
b'e' => match rstr[2] {b'n' => match rstr[3] {b'd' => Some(Ins::XEND),
_=>None}
_=>None}
b'l' => match rstr[2] {b'a' => match rstr[3] {b't' => Some(Ins::XLAT),
_=>None}
_=>None}
_=>None}
_=>None}5 => match rstr[0] {b'd' => match rstr[1] {b'i' => match rstr[2] {b'v' => match rstr[3]{b'p' => match rstr[4]{b'd' => Some(Ins::DIVPD),
b's' => Some(Ins::DIVPS),
_=>None}
b's' => match rstr[4]{b'd' => Some(Ins::DIVSD),
b's' => Some(Ins::DIVSS),
_=>None}
_=>None}
_=>None}
_=>None}
b'e' => match rstr[1] {b'n' => match rstr[2] {b't' => match rstr[3] {b'e' => match rstr[4] {b'r' => Some(Ins::ENTER),
_=>None}
_=>None}
_=>None}
_=>None}
b'f' => match rstr[1] {b'w' => match rstr[2] {b'a' => match rstr[3] {b'i' => match rstr[4] {b't' => Some(Ins::FWAIT),
_=>None}
_=>None}
_=>None}
_=>None}
b'i' => match rstr[1] {b'r' => match rstr[2] {b'e' => match rstr[3] {b't' => match rstr[4]{b'd' => Some(Ins::IRETD),
b'q' => Some(Ins::IRETQ),
_=>None}
_=>None}
_=>None}
_=>None}
b'o' => match rstr[1] {b'u' => match rstr[2] {b't' => match rstr[3] {b's' => match rstr[4]{b'b' => Some(Ins::OUTSB),
b'd' => Some(Ins::OUTSD),
b'w' => Some(Ins::OUTSW),
_=>None}
_=>None}
_=>None}
_=>None}
b'u' => match rstr[1] {b'i' => match rstr[2] {b'r' => match rstr[3] {b'e' => match rstr[4] {b't' => Some(Ins::UIRET),
_=>None}
_=>None}
_=>None}
_=>None}
b'w' => match rstr[1] {b'r' => match rstr[2]{b'm' => match rstr[3] {b's' => match rstr[4] {b'r' => Some(Ins::WRMSR),
_=>None}
_=>None}
b's' => match rstr[3] {b's' => match rstr[4]{b'd' => Some(Ins::WRSSD),
b'q' => Some(Ins::WRSSQ),
_=>None}
_=>None}
_=>None}
_=>None}
b'a' => match rstr[1]{b'd' => match rstr[2] {b'd' => match rstr[3]{b'p' => match rstr[4]{b'd' => Some(Ins::ADDPD),
b's' => Some(Ins::ADDPS),
_=>None}
b's' => match rstr[4]{b'd' => Some(Ins::ADDSD),
b's' => Some(Ins::ADDSS),
_=>None}
_=>None}
_=>None}
b'n' => match rstr[2] {b'd' => match rstr[3] {b'p' => match rstr[4]{b'd' => Some(Ins::ANDPD),
b's' => Some(Ins::ANDPS),
_=>None}
_=>None}
_=>None}
_=>None}
b'b' => match rstr[1]{b'e' => match rstr[2] {b'x' => match rstr[3] {b't' => match rstr[4] {b'r' => Some(Ins::BEXTR),
_=>None}
_=>None}
_=>None}
b's' => match rstr[2] {b'w' => match rstr[3] {b'a' => match rstr[4] {b'p' => Some(Ins::BSWAP),
_=>None}
_=>None}
_=>None}
_=>None}
b'c' => match rstr[1]{b'p' => match rstr[2] {b'u' => match rstr[3] {b'i' => match rstr[4] {b'd' => Some(Ins::CPUID),
_=>None}
_=>None}
_=>None}
b'r' => match rstr[2] {b'c' => match rstr[3] {b'3' => match rstr[4] {b'2' => Some(Ins::CRC32),
_=>None}
_=>None}
_=>None}
b'm' => match rstr[2]{b'o' => match rstr[3] {b'v' => match rstr[4]{b'a' => Some(Ins::CMOVA),
b'b' => Some(Ins::CMOVB),
b'c' => Some(Ins::CMOVC),
b'e' => Some(Ins::CMOVE),
b'g' => Some(Ins::CMOVG),
b'l' => Some(Ins::CMOVL),
b'o' => Some(Ins::CMOVO),
b'p' => Some(Ins::CMOVP),
b's' => Some(Ins::CMOVS),
b'z' => Some(Ins::CMOVZ),
_=>None}
_=>None}
b'p' => match rstr[3]{b'p' => match rstr[4]{b'd' => Some(Ins::CMPPD),
b's' => Some(Ins::CMPPS),
_=>None}
b's' => match rstr[4]{b'd' => Some(Ins::CMPSD),
b's' => Some(Ins::CMPSS),
_=>None}
_=>None}
_=>None}
_=>None}
b'l' => match rstr[1]{b'd' => match rstr[2] {b'd' => match rstr[3] {b'q' => match rstr[4] {b'u' => Some(Ins::LDDQU),
_=>None}
_=>None}
_=>None}
b'e' => match rstr[2] {b'a' => match rstr[3] {b'v' => match rstr[4] {b'e' => Some(Ins::LEAVE),
_=>None}
_=>None}
_=>None}
b'z' => match rstr[2] {b'c' => match rstr[3] {b'n' => match rstr[4] {b't' => Some(Ins::LZCNT),
_=>None}
_=>None}
_=>None}
b'o' => match rstr[2]{b'd' => match rstr[3] {b's' => match rstr[4]{b'b' => Some(Ins::LODSB),
b'd' => Some(Ins::LODSD),
b'q' => Some(Ins::LODSQ),
b'w' => Some(Ins::LODSW),
_=>None}
_=>None}
b'o' => match rstr[3] {b'p' => match rstr[4] {b'e' => Some(Ins::LOOPE),
_=>None}
_=>None}
_=>None}
_=>None}
b'm' => match rstr[1]{b'a' => match rstr[2] {b'x' => match rstr[3]{b'p' => match rstr[4]{b'd' => Some(Ins::MAXPD),
b's' => Some(Ins::MAXPS),
_=>None}
b's' => match rstr[4]{b'd' => Some(Ins::MAXSD),
b's' => Some(Ins::MAXSS),
_=>None}
_=>None}
_=>None}
b'i' => match rstr[2] {b'n' => match rstr[3]{b'p' => match rstr[4]{b'd' => Some(Ins::MINPD),
b's' => Some(Ins::MINPS),
_=>None}
b's' => match rstr[4]{b'd' => Some(Ins::MINSD),
b's' => Some(Ins::MINSS),
_=>None}
_=>None}
_=>None}
b'o' => match rstr[2] {b'v' => match rstr[3]{b'b' => match rstr[4] {b'e' => Some(Ins::MOVBE),
_=>None}
b'z' => match rstr[4] {b'x' => Some(Ins::MOVZX),
_=>None}
b's' => match rstr[4]{b'd' => Some(Ins::MOVSD),
b's' => Some(Ins::MOVSS),
_=>None}
_=>None}
_=>None}
b'u' => match rstr[2] {b'l' => match rstr[3]{b'p' => match rstr[4]{b'd' => Some(Ins::MULPD),
b's' => Some(Ins::MULPS),
_=>None}
b's' => match rstr[4]{b'd' => Some(Ins::MULSD),
b's' => Some(Ins::MULSS),
_=>None}
_=>None}
_=>None}
b'w' => match rstr[2] {b'a' => match rstr[3] {b'i' => match rstr[4] {b't' => Some(Ins::MWAIT),
_=>None}
_=>None}
_=>None}
_=>None}
b'p' => match rstr[1]{b'o' => match rstr[2] {b'p' => match rstr[3] {b'f' => match rstr[4]{b'd' => Some(Ins::POPFD),
b'q' => Some(Ins::POPFQ),
_=>None}
_=>None}
_=>None}
b't' => match rstr[2] {b'e' => match rstr[3] {b's' => match rstr[4] {b't' => Some(Ins::PTEST),
_=>None}
_=>None}
_=>None}
b'u' => match rstr[2] {b's' => match rstr[3] {b'h' => match rstr[4] {b'f' => Some(Ins::PUSHF),
_=>None}
_=>None}
_=>None}
b'a' => match rstr[2]{b'b' => match rstr[3] {b's' => match rstr[4]{b'b' => Some(Ins::PABSB),
b'd' => Some(Ins::PABSD),
b'w' => Some(Ins::PABSW),
_=>None}
_=>None}
b'd' => match rstr[3] {b'd' => match rstr[4]{b'b' => Some(Ins::PADDB),
b'd' => Some(Ins::PADDD),
b'q' => Some(Ins::PADDQ),
b'w' => Some(Ins::PADDW),
_=>None}
_=>None}
b'n' => match rstr[3] {b'd' => match rstr[4] {b'n' => Some(Ins::PANDN),
_=>None}
_=>None}
b'u' => match rstr[3] {b's' => match rstr[4] {b'e' => Some(Ins::PAUSE),
_=>None}
_=>None}
b'v' => match rstr[3] {b'g' => match rstr[4]{b'b' => Some(Ins::PAVGB),
b'w' => Some(Ins::PAVGW),
_=>None}
_=>None}
_=>None}
b's' => match rstr[2]{b'l' => match rstr[3] {b'l' => match rstr[4]{b'd' => Some(Ins::PSLLD),
b'q' => Some(Ins::PSLLQ),
b'w' => Some(Ins::PSLLW),
_=>None}
_=>None}
b'u' => match rstr[3] {b'b' => match rstr[4]{b'b' => Some(Ins::PSUBB),
b'd' => Some(Ins::PSUBD),
b'q' => Some(Ins::PSUBQ),
b'w' => Some(Ins::PSUBW),
_=>None}
_=>None}
b'r' => match rstr[3]{b'a' => match rstr[4]{b'd' => Some(Ins::PSRAD),
b'w' => Some(Ins::PSRAW),
_=>None}
b'l' => match rstr[4]{b'd' => Some(Ins::PSRLD),
b'q' => Some(Ins::PSRLQ),
b'w' => Some(Ins::PSRLW),
_=>None}
_=>None}
_=>None}
_=>None}
b'r' => match rstr[1]{b'c' => match rstr[2] {b'p' => match rstr[3]{b'p' => match rstr[4] {b's' => Some(Ins::RCPPS),
_=>None}
b's' => match rstr[4] {b's' => Some(Ins::RCPSS),
_=>None}
_=>None}
_=>None}
b'd' => match rstr[2]{b'm' => match rstr[3] {b's' => match rstr[4] {b'r' => Some(Ins::RDMSR),
_=>None}
_=>None}
b't' => match rstr[3] {b's' => match rstr[4] {b'c' => Some(Ins::RDTSC),
_=>None}
_=>None}
b'p' => match rstr[3]{b'i' => match rstr[4] {b'd' => Some(Ins::RDPID),
_=>None}
b'm' => match rstr[4] {b'c' => Some(Ins::RDPMC),
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[1]{b'c' => match rstr[2] {b'a' => match rstr[3] {b's' => match rstr[4]{b'b' => Some(Ins::SCASB),
b'd' => Some(Ins::SCASD),
b'q' => Some(Ins::SCASQ),
b'w' => Some(Ins::SCASW),
_=>None}
_=>None}
_=>None}
b'e' => match rstr[2] {b't' => match rstr[3]{b'a' => match rstr[4] {b'e' => Some(Ins::SETAE),
_=>None}
b'b' => match rstr[4] {b'e' => Some(Ins::SETBE),
_=>None}
b'g' => match rstr[4] {b'e' => Some(Ins::SETGE),
_=>None}
b'l' => match rstr[4] {b'e' => Some(Ins::SETLE),
_=>None}
b'n' => match rstr[4]{b'a' => Some(Ins::SETNA),
b'b' => Some(Ins::SETNB),
b'c' => Some(Ins::SETNC),
b'e' => Some(Ins::SETNE),
b'g' => Some(Ins::SETNG),
b'l' => Some(Ins::SETNL),
b'o' => Some(Ins::SETNO),
b'p' => Some(Ins::SETNP),
b's' => Some(Ins::SETNS),
b'z' => Some(Ins::SETNZ),
_=>None}
b'p' => match rstr[4]{b'e' => Some(Ins::SETPE),
b'o' => Some(Ins::SETPO),
_=>None}
_=>None}
_=>None}
b't' => match rstr[2] {b'o' => match rstr[3] {b's' => match rstr[4]{b'b' => Some(Ins::STOSB),
b'd' => Some(Ins::STOSD),
b'q' => Some(Ins::STOSQ),
b'w' => Some(Ins::STOSW),
_=>None}
_=>None}
_=>None}
b'u' => match rstr[2] {b'b' => match rstr[3]{b'p' => match rstr[4]{b'd' => Some(Ins::SUBPD),
b's' => Some(Ins::SUBPS),
_=>None}
b's' => match rstr[4]{b'd' => Some(Ins::SUBSD),
b's' => Some(Ins::SUBSS),
_=>None}
_=>None}
_=>None}
_=>None}
b'v' => match rstr[1]{b'd' => match rstr[2] {b'p' => match rstr[3] {b'p' => match rstr[4]{b'd' => Some(Ins::VDPPD),
b's' => Some(Ins::VDPPS),
_=>None}
_=>None}
_=>None}
b'm' => match rstr[2] {b'o' => match rstr[3] {b'v' => match rstr[4]{b'd' => Some(Ins::VMOVD),
b'q' => Some(Ins::VMOVQ),
_=>None}
_=>None}
_=>None}
b'o' => match rstr[2] {b'r' => match rstr[3] {b'p' => match rstr[4]{b'd' => Some(Ins::VORPD),
b's' => Some(Ins::VORPS),
_=>None}
_=>None}
_=>None}
b'p' => match rstr[2]{b'a' => match rstr[3] {b'n' => match rstr[4] {b'd' => Some(Ins::VPAND),
_=>None}
_=>None}
b'x' => match rstr[3] {b'o' => match rstr[4] {b'r' => Some(Ins::VPXOR),
_=>None}
_=>None}
_=>None}
_=>None}
b'x' => match rstr[1]{b'l' => match rstr[2] {b'a' => match rstr[3] {b't' => match rstr[4] {b'b' => Some(Ins::XLATB),
_=>None}
_=>None}
_=>None}
b'o' => match rstr[2] {b'r' => match rstr[3] {b'p' => match rstr[4]{b'd' => Some(Ins::XORPD),
b's' => Some(Ins::XORPS),
_=>None}
_=>None}
_=>None}
b's' => match rstr[2] {b'a' => match rstr[3] {b'v' => match rstr[4] {b'e' => Some(Ins::XSAVE),
_=>None}
_=>None}
_=>None}
b't' => match rstr[2] {b'e' => match rstr[3] {b's' => match rstr[4] {b't' => Some(Ins::XTEST),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}6 => match rstr[0] {b'b' => match rstr[1] {b'l' => match rstr[2] {b's' => match rstr[3] {b'm' => match rstr[4] {b's' => match rstr[5] {b'k' => Some(Ins::BLSMSK),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'i' => match rstr[1] {b'n' => match rstr[2] {b'v' => match rstr[3] {b'l' => match rstr[4] {b'p' => match rstr[5] {b'g' => Some(Ins::INVLPG),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'r' => match rstr[1] {b'd' => match rstr[2]{b'p' => match rstr[3] {b'k' => match rstr[4] {b'r' => match rstr[5] {b'u' => Some(Ins::RDPKRU),
_=>None}
_=>None}
_=>None}
b'r' => match rstr[3] {b'a' => match rstr[4] {b'n' => match rstr[5] {b'd' => Some(Ins::RDRAND),
_=>None}
_=>None}
_=>None}
b't' => match rstr[3] {b's' => match rstr[4] {b'c' => match rstr[5] {b'p' => Some(Ins::RDTSCP),
_=>None}
_=>None}
_=>None}
b's' => match rstr[3]{b'e' => match rstr[4] {b'e' => match rstr[5] {b'd' => Some(Ins::RDSEED),
_=>None}
_=>None}
b's' => match rstr[4] {b'p' => match rstr[5] {b'q' => Some(Ins::RDSSPQ),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'u' => match rstr[1] {b'm' => match rstr[2] {b'w' => match rstr[3] {b'a' => match rstr[4] {b'i' => match rstr[5] {b't' => Some(Ins::UMWAIT),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'a' => match rstr[1]{b'e' => match rstr[2] {b's' => match rstr[3]{b'd' => match rstr[4] {b'e' => match rstr[5] {b'c' => Some(Ins::AESDEC),
_=>None}
_=>None}
b'e' => match rstr[4] {b'n' => match rstr[5] {b'c' => Some(Ins::AESENC),
_=>None}
_=>None}
b'i' => match rstr[4] {b'm' => match rstr[5] {b'c' => Some(Ins::AESIMC),
_=>None}
_=>None}
_=>None}
_=>None}
b'n' => match rstr[2] {b'd' => match rstr[3] {b'n' => match rstr[4] {b'p' => match rstr[5]{b'd' => Some(Ins::ANDNPD),
b's' => Some(Ins::ANDNPS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'c' => match rstr[1]{b'o' => match rstr[2] {b'm' => match rstr[3] {b'i' => match rstr[4] {b's' => match rstr[5]{b'd' => Some(Ins::COMISD),
b's' => Some(Ins::COMISS),
_=>None}
_=>None}
_=>None}
_=>None}
b'm' => match rstr[2]{b'o' => match rstr[3] {b'v' => match rstr[4]{b'a' => match rstr[5] {b'e' => Some(Ins::CMOVAE),
_=>None}
b'b' => match rstr[5] {b'e' => Some(Ins::CMOVBE),
_=>None}
b'g' => match rstr[5] {b'e' => Some(Ins::CMOVGE),
_=>None}
b'l' => match rstr[5] {b'e' => Some(Ins::CMOVLE),
_=>None}
b'n' => match rstr[5]{b'a' => Some(Ins::CMOVNA),
b'b' => Some(Ins::CMOVNB),
b'c' => Some(Ins::CMOVNC),
b'e' => Some(Ins::CMOVNE),
b'g' => Some(Ins::CMOVNG),
b'l' => Some(Ins::CMOVNL),
b'o' => Some(Ins::CMOVNO),
b'p' => Some(Ins::CMOVNP),
b's' => Some(Ins::CMOVNS),
b'z' => Some(Ins::CMOVNZ),
_=>None}
b'p' => match rstr[5]{b'e' => Some(Ins::CMOVPE),
b'o' => Some(Ins::CMOVPO),
_=>None}
_=>None}
_=>None}
b'p' => match rstr[3] {b's' => match rstr[4] {b't' => match rstr[5] {b'r' => Some(Ins::CMPSTR),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'h' => match rstr[1]{b'a' => match rstr[2] {b'd' => match rstr[3] {b'd' => match rstr[4] {b'p' => match rstr[5]{b'd' => Some(Ins::HADDPD),
b's' => Some(Ins::HADDPS),
_=>None}
_=>None}
_=>None}
_=>None}
b'r' => match rstr[2] {b'e' => match rstr[3] {b's' => match rstr[4] {b'e' => match rstr[5] {b't' => Some(Ins::HRESET),
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[2] {b'u' => match rstr[3] {b'b' => match rstr[4] {b'p' => match rstr[5]{b'd' => Some(Ins::HSUBPD),
b's' => Some(Ins::HSUBPS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'l' => match rstr[1]{b'f' => match rstr[2] {b'e' => match rstr[3] {b'n' => match rstr[4] {b'c' => match rstr[5] {b'e' => Some(Ins::LFENCE),
_=>None}
_=>None}
_=>None}
_=>None}
b'o' => match rstr[2] {b'o' => match rstr[3] {b'p' => match rstr[4] {b'n' => match rstr[5] {b'e' => Some(Ins::LOOPNE),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'm' => match rstr[1]{b'f' => match rstr[2] {b'e' => match rstr[3] {b'n' => match rstr[4] {b'c' => match rstr[5] {b'e' => Some(Ins::MFENCE),
_=>None}
_=>None}
_=>None}
_=>None}
b'o' => match rstr[2] {b'v' => match rstr[3]{b'a' => match rstr[4] {b'p' => match rstr[5]{b'd' => Some(Ins::MOVAPD),
b's' => Some(Ins::MOVAPS),
_=>None}
_=>None}
b'd' => match rstr[4] {b'q' => match rstr[5] {b'a' => Some(Ins::MOVDQA),
_=>None}
_=>None}
b'h' => match rstr[4] {b'p' => match rstr[5]{b'd' => Some(Ins::MOVHPD),
b's' => Some(Ins::MOVHPS),
_=>None}
_=>None}
b'l' => match rstr[4] {b'p' => match rstr[5]{b'd' => Some(Ins::MOVLPD),
b's' => Some(Ins::MOVLPS),
_=>None}
_=>None}
b'n' => match rstr[4] {b't' => match rstr[5] {b'i' => Some(Ins::MOVNTI),
_=>None}
_=>None}
b's' => match rstr[4] {b't' => match rstr[5] {b'r' => Some(Ins::MOVSTR),
_=>None}
_=>None}
b'u' => match rstr[4] {b'p' => match rstr[5]{b'd' => Some(Ins::MOVUPD),
b's' => Some(Ins::MOVUPS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'p' => match rstr[1]{b'a' => match rstr[2] {b'd' => match rstr[3] {b'd' => match rstr[4] {b's' => match rstr[5]{b'b' => Some(Ins::PADDSB),
b'w' => Some(Ins::PADDSW),
_=>None}
_=>None}
_=>None}
_=>None}
b'e' => match rstr[2] {b'x' => match rstr[3] {b't' => match rstr[4] {b'r' => match rstr[5]{b'b' => Some(Ins::PEXTRB),
b'd' => Some(Ins::PEXTRD),
b'q' => Some(Ins::PEXTRQ),
b'w' => Some(Ins::PEXTRW),
_=>None}
_=>None}
_=>None}
_=>None}
b'i' => match rstr[2] {b'n' => match rstr[3] {b's' => match rstr[4] {b'r' => match rstr[5]{b'b' => Some(Ins::PINSRB),
b'd' => Some(Ins::PINSRD),
b'q' => Some(Ins::PINSRQ),
b'w' => Some(Ins::PINSRW),
_=>None}
_=>None}
_=>None}
_=>None}
b'o' => match rstr[2] {b'p' => match rstr[3] {b'c' => match rstr[4] {b'n' => match rstr[5] {b't' => Some(Ins::POPCNT),
_=>None}
_=>None}
_=>None}
_=>None}
b'u' => match rstr[2] {b's' => match rstr[3] {b'h' => match rstr[4] {b'f' => match rstr[5]{b'd' => Some(Ins::PUSHFD),
b'q' => Some(Ins::PUSHFQ),
_=>None}
_=>None}
_=>None}
_=>None}
b'h' => match rstr[2]{b'a' => match rstr[3] {b'd' => match rstr[4] {b'd' => match rstr[5]{b'd' => Some(Ins::PHADDD),
b'w' => Some(Ins::PHADDW),
_=>None}
_=>None}
_=>None}
b's' => match rstr[3] {b'u' => match rstr[4] {b'b' => match rstr[5]{b'd' => Some(Ins::PHSUBD),
b'w' => Some(Ins::PHSUBW),
_=>None}
_=>None}
_=>None}
_=>None}
b'm' => match rstr[2]{b'a' => match rstr[3] {b'x' => match rstr[4]{b's' => match rstr[5]{b'b' => Some(Ins::PMAXSB),
b'd' => Some(Ins::PMAXSD),
b'w' => Some(Ins::PMAXSW),
_=>None}
b'u' => match rstr[5]{b'd' => Some(Ins::PMAXUD),
b'w' => Some(Ins::PMAXUW),
_=>None}
_=>None}
_=>None}
b'i' => match rstr[3] {b'n' => match rstr[4]{b's' => match rstr[5]{b'b' => Some(Ins::PMINSB),
b'd' => Some(Ins::PMINSD),
b'w' => Some(Ins::PMINSW),
_=>None}
b'u' => match rstr[5] {b'w' => Some(Ins::PMINUW),
_=>None}
_=>None}
_=>None}
b'u' => match rstr[3] {b'l' => match rstr[4]{b'd' => match rstr[5] {b'q' => Some(Ins::PMULDQ),
_=>None}
b'h' => match rstr[5] {b'w' => Some(Ins::PMULHW),
_=>None}
b'l' => match rstr[5]{b'd' => Some(Ins::PMULLD),
b'w' => Some(Ins::PMULLW),
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[2]{b'h' => match rstr[3] {b'u' => match rstr[4] {b'f' => match rstr[5]{b'b' => Some(Ins::PSHUFB),
b'd' => Some(Ins::PSHUFD),
_=>None}
_=>None}
_=>None}
b'i' => match rstr[3] {b'g' => match rstr[4] {b'n' => match rstr[5]{b'b' => Some(Ins::PSIGNB),
b'd' => Some(Ins::PSIGND),
b'w' => Some(Ins::PSIGNW),
_=>None}
_=>None}
_=>None}
b'l' => match rstr[3] {b'l' => match rstr[4] {b'd' => match rstr[5] {b'q' => Some(Ins::PSLLDQ),
_=>None}
_=>None}
_=>None}
b'r' => match rstr[3] {b'l' => match rstr[4] {b'd' => match rstr[5] {b'q' => Some(Ins::PSRLDQ),
_=>None}
_=>None}
_=>None}
b'u' => match rstr[3] {b'b' => match rstr[4] {b's' => match rstr[5]{b'b' => Some(Ins::PSUBSB),
b'w' => Some(Ins::PSUBSW),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[1]{b'e' => match rstr[2] {b't' => match rstr[3] {b'n' => match rstr[4]{b'a' => match rstr[5] {b'e' => Some(Ins::SETNAE),
_=>None}
b'b' => match rstr[5] {b'e' => Some(Ins::SETNBE),
_=>None}
b'g' => match rstr[5] {b'e' => Some(Ins::SETNGE),
_=>None}
b'l' => match rstr[5] {b'e' => Some(Ins::SETNLE),
_=>None}
_=>None}
_=>None}
_=>None}
b'f' => match rstr[2] {b'e' => match rstr[3] {b'n' => match rstr[4] {b'c' => match rstr[5] {b'e' => Some(Ins::SFENCE),
_=>None}
_=>None}
_=>None}
_=>None}
b'h' => match rstr[2] {b'u' => match rstr[3] {b'f' => match rstr[4] {b'p' => match rstr[5] {b's' => Some(Ins::SHUFPS),
_=>None}
_=>None}
_=>None}
_=>None}
b'q' => match rstr[2] {b'r' => match rstr[3] {b't' => match rstr[4]{b'p' => match rstr[5]{b'd' => Some(Ins::SQRTPD),
b's' => Some(Ins::SQRTPS),
_=>None}
b's' => match rstr[5]{b'd' => Some(Ins::SQRTSD),
b's' => Some(Ins::SQRTSS),
_=>None}
_=>None}
_=>None}
_=>None}
b'y' => match rstr[2] {b's' => match rstr[3] {b'r' => match rstr[4] {b'e' => match rstr[5] {b't' => Some(Ins::SYSRET),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b't' => match rstr[1]{b'e' => match rstr[2] {b's' => match rstr[3] {b't' => match rstr[4] {b'u' => match rstr[5] {b'i' => Some(Ins::TESTUI),
_=>None}
_=>None}
_=>None}
_=>None}
b'p' => match rstr[2] {b'a' => match rstr[3] {b'u' => match rstr[4] {b's' => match rstr[5] {b'e' => Some(Ins::TPAUSE),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'v' => match rstr[1]{b'c' => match rstr[2] {b'm' => match rstr[3] {b'p' => match rstr[4]{b'p' => match rstr[5]{b'd' => Some(Ins::VCMPPD),
b's' => Some(Ins::VCMPPS),
_=>None}
b's' => match rstr[5]{b'd' => Some(Ins::VCMPSD),
b's' => Some(Ins::VCMPSS),
_=>None}
_=>None}
_=>None}
_=>None}
b'd' => match rstr[2] {b'i' => match rstr[3] {b'v' => match rstr[4]{b'p' => match rstr[5]{b'd' => Some(Ins::VDIVPD),
b's' => Some(Ins::VDIVPS),
_=>None}
b's' => match rstr[5]{b'd' => Some(Ins::VDIVSD),
b's' => Some(Ins::VDIVSS),
_=>None}
_=>None}
_=>None}
_=>None}
b'l' => match rstr[2] {b'd' => match rstr[3] {b'd' => match rstr[4] {b'q' => match rstr[5] {b'u' => Some(Ins::VLDDQU),
_=>None}
_=>None}
_=>None}
_=>None}
b'r' => match rstr[2] {b'c' => match rstr[3] {b'p' => match rstr[4]{b'p' => match rstr[5] {b's' => Some(Ins::VRCPPS),
_=>None}
b's' => match rstr[5] {b's' => Some(Ins::VRCPSS),
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[2] {b'u' => match rstr[3] {b'b' => match rstr[4]{b'p' => match rstr[5]{b'd' => Some(Ins::VSUBPD),
b's' => Some(Ins::VSUBPS),
_=>None}
b's' => match rstr[5]{b'd' => Some(Ins::VSUBSD),
b's' => Some(Ins::VSUBSS),
_=>None}
_=>None}
_=>None}
_=>None}
b'x' => match rstr[2] {b'o' => match rstr[3] {b'r' => match rstr[4] {b'p' => match rstr[5]{b'd' => Some(Ins::VXORPD),
b's' => Some(Ins::VXORPS),
_=>None}
_=>None}
_=>None}
_=>None}
b'a' => match rstr[2]{b'd' => match rstr[3] {b'd' => match rstr[4]{b'p' => match rstr[5]{b'd' => Some(Ins::VADDPD),
b's' => Some(Ins::VADDPS),
_=>None}
b's' => match rstr[5]{b'd' => Some(Ins::VADDSD),
b's' => Some(Ins::VADDSS),
_=>None}
_=>None}
_=>None}
b'n' => match rstr[3] {b'd' => match rstr[4] {b'p' => match rstr[5]{b'd' => Some(Ins::VANDPD),
b's' => Some(Ins::VANDPS),
_=>None}
_=>None}
_=>None}
_=>None}
b'm' => match rstr[2]{b'a' => match rstr[3] {b'x' => match rstr[4]{b'p' => match rstr[5]{b'd' => Some(Ins::VMAXPD),
b's' => Some(Ins::VMAXPS),
_=>None}
b's' => match rstr[5]{b'd' => Some(Ins::VMAXSD),
b's' => Some(Ins::VMAXSS),
_=>None}
_=>None}
_=>None}
b'i' => match rstr[3] {b'n' => match rstr[4]{b'p' => match rstr[5]{b'd' => Some(Ins::VMINPD),
b's' => Some(Ins::VMINPS),
_=>None}
b's' => match rstr[5]{b'd' => Some(Ins::VMINSD),
b's' => Some(Ins::VMINSS),
_=>None}
_=>None}
_=>None}
b'o' => match rstr[3] {b'v' => match rstr[4] {b's' => match rstr[5]{b'd' => Some(Ins::VMOVSD),
b's' => Some(Ins::VMOVSS),
_=>None}
_=>None}
_=>None}
b'u' => match rstr[3] {b'l' => match rstr[4]{b'p' => match rstr[5]{b'd' => Some(Ins::VMULPD),
b's' => Some(Ins::VMULPS),
_=>None}
b's' => match rstr[5]{b'd' => Some(Ins::VMULSD),
b's' => Some(Ins::VMULSS),
_=>None}
_=>None}
_=>None}
_=>None}
b'p' => match rstr[2]{b't' => match rstr[3] {b'e' => match rstr[4] {b's' => match rstr[5] {b't' => Some(Ins::VPTEST),
_=>None}
_=>None}
_=>None}
b'a' => match rstr[3]{b'd' => match rstr[4] {b'd' => match rstr[5]{b'b' => Some(Ins::VPADDB),
b'd' => Some(Ins::VPADDD),
b'q' => Some(Ins::VPADDQ),
b'w' => Some(Ins::VPADDW),
_=>None}
_=>None}
b'n' => match rstr[4] {b'd' => match rstr[5] {b'n' => Some(Ins::VPANDN),
_=>None}
_=>None}
b'v' => match rstr[4] {b'g' => match rstr[5]{b'b' => Some(Ins::VPAVGB),
b'w' => Some(Ins::VPAVGW),
_=>None}
_=>None}
_=>None}
b's' => match rstr[3]{b'l' => match rstr[4] {b'l' => match rstr[5]{b'd' => Some(Ins::VPSLLD),
b'q' => Some(Ins::VPSLLQ),
b'w' => Some(Ins::VPSLLW),
_=>None}
_=>None}
b'u' => match rstr[4] {b'b' => match rstr[5]{b'b' => Some(Ins::VPSUBB),
b'd' => Some(Ins::VPSUBD),
b'q' => Some(Ins::VPSUBQ),
b'w' => Some(Ins::VPSUBW),
_=>None}
_=>None}
b'r' => match rstr[4]{b'a' => match rstr[5]{b'd' => Some(Ins::VPSRAD),
b'w' => Some(Ins::VPSRAW),
_=>None}
b'l' => match rstr[5]{b'd' => Some(Ins::VPSRLD),
b'q' => Some(Ins::VPSRLQ),
b'w' => Some(Ins::VPSRLW),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'w' => match rstr[1]{b'b' => match rstr[2] {b'i' => match rstr[3] {b'n' => match rstr[4] {b'v' => match rstr[5] {b'd' => Some(Ins::WBINVD),
_=>None}
_=>None}
_=>None}
_=>None}
b'r' => match rstr[2]{b'p' => match rstr[3] {b'k' => match rstr[4] {b'r' => match rstr[5] {b'u' => Some(Ins::WRPKRU),
_=>None}
_=>None}
_=>None}
b'u' => match rstr[3] {b's' => match rstr[4] {b's' => match rstr[5]{b'd' => Some(Ins::WRUSSD),
b'q' => Some(Ins::WRUSSQ),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'x' => match rstr[1]{b'a' => match rstr[2] {b'b' => match rstr[3] {b'o' => match rstr[4] {b'r' => match rstr[5] {b't' => Some(Ins::XABORT),
_=>None}
_=>None}
_=>None}
_=>None}
b'b' => match rstr[2] {b'e' => match rstr[3] {b'g' => match rstr[4] {b'i' => match rstr[5] {b'n' => Some(Ins::XBEGIN),
_=>None}
_=>None}
_=>None}
_=>None}
b'g' => match rstr[2] {b'e' => match rstr[3] {b't' => match rstr[4] {b'b' => match rstr[5] {b'v' => Some(Ins::XGETBV),
_=>None}
_=>None}
_=>None}
_=>None}
b'r' => match rstr[2] {b's' => match rstr[3] {b't' => match rstr[4] {b'o' => match rstr[5] {b'r' => Some(Ins::XRSTOR),
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[2]{b'a' => match rstr[3] {b'v' => match rstr[4] {b'e' => match rstr[5]{b'c' => Some(Ins::XSAVEC),
b's' => Some(Ins::XSAVES),
_=>None}
_=>None}
_=>None}
b'e' => match rstr[3] {b't' => match rstr[4] {b'b' => match rstr[5] {b'v' => Some(Ins::XSETBV),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}7 => match rstr[0] {b'b' => match rstr[1] {b'l' => match rstr[2] {b'e' => match rstr[3] {b'n' => match rstr[4] {b'd' => match rstr[5] {b'p' => match rstr[6]{b'd' => Some(Ins::BLENDPD),
b's' => Some(Ins::BLENDPS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'e' => match rstr[1] {b'n' => match rstr[2] {b'd' => match rstr[3] {b'b' => match rstr[4] {b'r' => match rstr[5]{b'3' => match rstr[6] {b'2' => Some(Ins::ENDBR32),
_=>None}
b'6' => match rstr[6] {b'4' => Some(Ins::ENDBR64),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'i' => match rstr[1] {b'n' => match rstr[2] {b'v' => match rstr[3] {b'p' => match rstr[4] {b'c' => match rstr[5] {b'i' => match rstr[6] {b'd' => Some(Ins::INVPCID),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'l' => match rstr[1] {b'd' => match rstr[2] {b'm' => match rstr[3] {b'x' => match rstr[4] {b'c' => match rstr[5] {b's' => match rstr[6] {b'r' => Some(Ins::LDMXCSR),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'u' => match rstr[1] {b'c' => match rstr[2] {b'o' => match rstr[3] {b'm' => match rstr[4] {b'i' => match rstr[5] {b's' => match rstr[6]{b'd' => Some(Ins::UCOMISD),
b's' => Some(Ins::UCOMISS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'c' => match rstr[1]{b'l' => match rstr[2] {b'f' => match rstr[3] {b'l' => match rstr[4] {b'u' => match rstr[5] {b's' => match rstr[6] {b'h' => Some(Ins::CLFLUSH),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'm' => match rstr[2]{b'o' => match rstr[3] {b'v' => match rstr[4] {b'n' => match rstr[5]{b'a' => match rstr[6] {b'e' => Some(Ins::CMOVNAE),
_=>None}
b'b' => match rstr[6] {b'e' => Some(Ins::CMOVNBE),
_=>None}
b'g' => match rstr[6] {b'e' => Some(Ins::CMOVNGE),
_=>None}
b'l' => match rstr[6] {b'e' => Some(Ins::CMOVNLE),
_=>None}
_=>None}
_=>None}
_=>None}
b'p' => match rstr[3]{b's' => match rstr[4] {b't' => match rstr[5] {b'r' => match rstr[6]{b'd' => Some(Ins::CMPSTRD),
b'q' => Some(Ins::CMPSTRQ),
b'w' => Some(Ins::CMPSTRW),
_=>None}
_=>None}
_=>None}
b'x' => match rstr[4] {b'c' => match rstr[5] {b'h' => match rstr[6] {b'g' => Some(Ins::CMPXCHG),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'm' => match rstr[1]{b'o' => match rstr[2]{b'n' => match rstr[3] {b'i' => match rstr[4] {b't' => match rstr[5] {b'o' => match rstr[6] {b'r' => Some(Ins::MONITOR),
_=>None}
_=>None}
_=>None}
_=>None}
b'v' => match rstr[3]{b'h' => match rstr[4] {b'l' => match rstr[5] {b'p' => match rstr[6] {b's' => Some(Ins::MOVHLPS),
_=>None}
_=>None}
_=>None}
b'l' => match rstr[4] {b'h' => match rstr[5] {b'p' => match rstr[6] {b's' => Some(Ins::MOVLHPS),
_=>None}
_=>None}
_=>None}
b'n' => match rstr[4] {b't' => match rstr[5]{b'd' => match rstr[6] {b'q' => Some(Ins::MOVNTDQ),
_=>None}
b'p' => match rstr[6] {b'd' => Some(Ins::MOVNTPD),
_=>None}
_=>None}
_=>None}
b'q' => match rstr[4] {b'2' => match rstr[5] {b'd' => match rstr[6] {b'q' => Some(Ins::MOVQ2DQ),
_=>None}
_=>None}
_=>None}
b's' => match rstr[4] {b't' => match rstr[5] {b'r' => match rstr[6]{b'b' => Some(Ins::MOVSTRB),
b'd' => Some(Ins::MOVSTRD),
b'q' => Some(Ins::MOVSTRQ),
b'w' => Some(Ins::MOVSTRW),
_=>None}
_=>None}
_=>None}
b'd' => match rstr[4]{b'd' => match rstr[5] {b'u' => match rstr[6] {b'p' => Some(Ins::MOVDDUP),
_=>None}
_=>None}
b'i' => match rstr[5] {b'r' => match rstr[6] {b'i' => Some(Ins::MOVDIRI),
_=>None}
_=>None}
b'q' => match rstr[5] {b'2' => match rstr[6] {b'q' => Some(Ins::MOVDQ2Q),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'p' => match rstr[2] {b's' => match rstr[3] {b'a' => match rstr[4] {b'd' => match rstr[5] {b'b' => match rstr[6] {b'w' => Some(Ins::MPSADBW),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'p' => match rstr[1]{b'b' => match rstr[2] {b'l' => match rstr[3] {b'e' => match rstr[4] {b'n' => match rstr[5] {b'd' => match rstr[6] {b'w' => Some(Ins::PBLENDW),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'c' => match rstr[2] {b'm' => match rstr[3] {b'p' => match rstr[4]{b'e' => match rstr[5] {b'q' => match rstr[6]{b'b' => Some(Ins::PCMPEQB),
b'd' => Some(Ins::PCMPEQD),
b'q' => Some(Ins::PCMPEQQ),
b'w' => Some(Ins::PCMPEQW),
_=>None}
_=>None}
b'g' => match rstr[5] {b't' => match rstr[6]{b'b' => Some(Ins::PCMPGTB),
b'd' => Some(Ins::PCMPGTD),
b'q' => Some(Ins::PCMPGTQ),
b'w' => Some(Ins::PCMPGTW),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'a' => match rstr[2]{b'd' => match rstr[3] {b'd' => match rstr[4] {b'u' => match rstr[5] {b's' => match rstr[6]{b'b' => Some(Ins::PADDUSB),
b'w' => Some(Ins::PADDUSW),
_=>None}
_=>None}
_=>None}
_=>None}
b'l' => match rstr[3] {b'i' => match rstr[4] {b'g' => match rstr[5] {b'n' => match rstr[6] {b'r' => Some(Ins::PALIGNR),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'h' => match rstr[2]{b'a' => match rstr[3] {b'd' => match rstr[4] {b'd' => match rstr[5] {b's' => match rstr[6] {b'w' => Some(Ins::PHADDSW),
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[3] {b'u' => match rstr[4] {b'b' => match rstr[5] {b's' => match rstr[6] {b'w' => Some(Ins::PHSUBSW),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'm' => match rstr[2]{b'a' => match rstr[3] {b'd' => match rstr[4] {b'd' => match rstr[5] {b'w' => match rstr[6] {b'd' => Some(Ins::PMADDWD),
_=>None}
_=>None}
_=>None}
_=>None}
b'u' => match rstr[3] {b'l' => match rstr[4]{b'h' => match rstr[5] {b'u' => match rstr[6] {b'w' => Some(Ins::PMULHUW),
_=>None}
_=>None}
b'u' => match rstr[5] {b'd' => match rstr[6] {b'q' => Some(Ins::PMULUDQ),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[2]{b'h' => match rstr[3] {b'u' => match rstr[4] {b'f' => match rstr[5]{b'h' => match rstr[6] {b'w' => Some(Ins::PSHUFHW),
_=>None}
b'l' => match rstr[6] {b'w' => Some(Ins::PSHUFLW),
_=>None}
_=>None}
_=>None}
_=>None}
b'u' => match rstr[3] {b'b' => match rstr[4] {b'u' => match rstr[5] {b's' => match rstr[6]{b'b' => Some(Ins::PSUBUSB),
b'w' => Some(Ins::PSUBUSW),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'r' => match rstr[1]{b'o' => match rstr[2] {b'u' => match rstr[3] {b'n' => match rstr[4] {b'd' => match rstr[5]{b'p' => match rstr[6]{b'd' => Some(Ins::ROUNDPD),
b's' => Some(Ins::ROUNDPS),
_=>None}
b's' => match rstr[6]{b'd' => Some(Ins::ROUNDSD),
b's' => Some(Ins::ROUNDSS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[2] {b'q' => match rstr[3] {b'r' => match rstr[4] {b't' => match rstr[5]{b'p' => match rstr[6] {b's' => Some(Ins::RSQRTPS),
_=>None}
b's' => match rstr[6] {b's' => Some(Ins::RSQRTSS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[1]{b'e' => match rstr[2] {b't' => match rstr[3] {b's' => match rstr[4] {b's' => match rstr[5] {b'b' => match rstr[6] {b'y' => Some(Ins::SETSSBY),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b't' => match rstr[2] {b'm' => match rstr[3] {b'x' => match rstr[4] {b'c' => match rstr[5] {b's' => match rstr[6] {b'r' => Some(Ins::STMXCSR),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'y' => match rstr[2] {b's' => match rstr[3]{b'c' => match rstr[4] {b'a' => match rstr[5] {b'l' => match rstr[6] {b'l' => Some(Ins::SYSCALL),
_=>None}
_=>None}
_=>None}
b'e' => match rstr[4] {b'x' => match rstr[5] {b'i' => match rstr[6] {b't' => Some(Ins::SYSEXIT),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'v' => match rstr[1]{b'c' => match rstr[2] {b'o' => match rstr[3] {b'm' => match rstr[4] {b'i' => match rstr[5] {b's' => match rstr[6]{b'd' => Some(Ins::VCOMISD),
b's' => Some(Ins::VCOMISS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'm' => match rstr[2] {b'o' => match rstr[3] {b'v' => match rstr[4]{b'a' => match rstr[5] {b'p' => match rstr[6]{b'd' => Some(Ins::VMOVAPD),
b's' => Some(Ins::VMOVAPS),
_=>None}
_=>None}
b'd' => match rstr[5] {b'q' => match rstr[6] {b'a' => Some(Ins::VMOVDQA),
_=>None}
_=>None}
b'h' => match rstr[5] {b'p' => match rstr[6]{b'd' => Some(Ins::VMOVHPD),
b's' => Some(Ins::VMOVHPS),
_=>None}
_=>None}
b'l' => match rstr[5] {b'p' => match rstr[6]{b'd' => Some(Ins::VMOVLPD),
b's' => Some(Ins::VMOVLPS),
_=>None}
_=>None}
b'u' => match rstr[5] {b'p' => match rstr[6]{b'd' => Some(Ins::VMOVUPD),
b's' => Some(Ins::VMOVUPS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'a' => match rstr[2]{b'e' => match rstr[3] {b's' => match rstr[4]{b'd' => match rstr[5] {b'e' => match rstr[6] {b'c' => Some(Ins::VAESDEC),
_=>None}
_=>None}
b'e' => match rstr[5] {b'n' => match rstr[6] {b'c' => Some(Ins::VAESENC),
_=>None}
_=>None}
b'i' => match rstr[5] {b'm' => match rstr[6] {b'c' => Some(Ins::VAESIMC),
_=>None}
_=>None}
_=>None}
_=>None}
b'n' => match rstr[3] {b'd' => match rstr[4] {b'n' => match rstr[5] {b'p' => match rstr[6]{b'd' => Some(Ins::VANDNPD),
b's' => Some(Ins::VANDNPS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'h' => match rstr[2]{b'a' => match rstr[3] {b'd' => match rstr[4] {b'd' => match rstr[5] {b'p' => match rstr[6]{b'd' => Some(Ins::VHADDPD),
b's' => Some(Ins::VHADDPS),
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[3] {b'u' => match rstr[4] {b'b' => match rstr[5] {b'p' => match rstr[6]{b'd' => Some(Ins::VHSUBPD),
b's' => Some(Ins::VHSUBPS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'p' => match rstr[2]{b'a' => match rstr[3] {b'd' => match rstr[4] {b'd' => match rstr[5] {b's' => match rstr[6]{b'b' => Some(Ins::VPADDSB),
b'w' => Some(Ins::VPADDSW),
_=>None}
_=>None}
_=>None}
_=>None}
b'e' => match rstr[3] {b'x' => match rstr[4] {b't' => match rstr[5] {b'r' => match rstr[6]{b'b' => Some(Ins::VPEXTRB),
b'd' => Some(Ins::VPEXTRD),
b'q' => Some(Ins::VPEXTRQ),
b'w' => Some(Ins::VPEXTRW),
_=>None}
_=>None}
_=>None}
_=>None}
b'i' => match rstr[3] {b'n' => match rstr[4] {b's' => match rstr[5] {b'r' => match rstr[6]{b'b' => Some(Ins::VPINSRB),
b'd' => Some(Ins::VPINSRD),
b'q' => Some(Ins::VPINSRQ),
b'w' => Some(Ins::VPINSRW),
_=>None}
_=>None}
_=>None}
_=>None}
b'h' => match rstr[3]{b'a' => match rstr[4] {b'd' => match rstr[5] {b'd' => match rstr[6]{b'd' => Some(Ins::VPHADDD),
b'w' => Some(Ins::VPHADDW),
_=>None}
_=>None}
_=>None}
b's' => match rstr[4] {b'u' => match rstr[5] {b'b' => match rstr[6]{b'd' => Some(Ins::VPHSUBD),
b'w' => Some(Ins::VPHSUBW),
_=>None}
_=>None}
_=>None}
_=>None}
b'm' => match rstr[3]{b'a' => match rstr[4] {b'x' => match rstr[5]{b's' => match rstr[6]{b'b' => Some(Ins::VPMAXSB),
b'd' => Some(Ins::VPMAXSD),
b'w' => Some(Ins::VPMAXSW),
_=>None}
b'u' => match rstr[6]{b'b' => Some(Ins::VPMAXUB),
b'd' => Some(Ins::VPMAXUD),
b'w' => Some(Ins::VPMAXUW),
_=>None}
_=>None}
_=>None}
b'i' => match rstr[4] {b'n' => match rstr[5]{b's' => match rstr[6]{b'b' => Some(Ins::VPMINSB),
b'd' => Some(Ins::VPMINSD),
b'w' => Some(Ins::VPMINSW),
_=>None}
b'u' => match rstr[6]{b'b' => Some(Ins::VPMINUB),
b'w' => Some(Ins::VPMINUW),
_=>None}
_=>None}
_=>None}
b'u' => match rstr[4] {b'l' => match rstr[5]{b'd' => match rstr[6] {b'q' => Some(Ins::VPMULDQ),
_=>None}
b'h' => match rstr[6] {b'w' => Some(Ins::VPMULHW),
_=>None}
b'l' => match rstr[6]{b'd' => Some(Ins::VPMULLD),
b'w' => Some(Ins::VPMULLW),
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[3]{b'i' => match rstr[4] {b'g' => match rstr[5] {b'n' => match rstr[6]{b'b' => Some(Ins::VPSIGNB),
b'd' => Some(Ins::VPSIGND),
b'w' => Some(Ins::VPSIGNW),
_=>None}
_=>None}
_=>None}
b'r' => match rstr[4] {b'l' => match rstr[5] {b'd' => match rstr[6] {b'q' => Some(Ins::VPSRLDQ),
_=>None}
_=>None}
_=>None}
b'u' => match rstr[4] {b'b' => match rstr[5] {b's' => match rstr[6]{b'b' => Some(Ins::VPSUBSB),
b'w' => Some(Ins::VPSUBSW),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[2]{b'h' => match rstr[3] {b'u' => match rstr[4] {b'f' => match rstr[5] {b'p' => match rstr[6] {b's' => Some(Ins::VSHUFPS),
_=>None}
_=>None}
_=>None}
_=>None}
b'q' => match rstr[3] {b'r' => match rstr[4] {b't' => match rstr[5]{b'p' => match rstr[6]{b'd' => Some(Ins::VSQRTPD),
b's' => Some(Ins::VSQRTPS),
_=>None}
b's' => match rstr[6]{b'd' => Some(Ins::VSQRTSD),
b's' => Some(Ins::VSQRTSS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'x' => match rstr[1]{b'r' => match rstr[2] {b's' => match rstr[3] {b't' => match rstr[4] {b'o' => match rstr[5] {b'r' => match rstr[6] {b's' => Some(Ins::XRSTORS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[2] {b'a' => match rstr[3] {b'v' => match rstr[4] {b'e' => match rstr[5] {b'6' => match rstr[6] {b'4' => Some(Ins::XSAVE64),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}8 => match rstr[0] {b'a' => match rstr[1] {b'd' => match rstr[2] {b'd' => match rstr[3] {b's' => match rstr[4] {b'u' => match rstr[5] {b'b' => match rstr[6] {b'p' => match rstr[7]{b'd' => Some(Ins::ADDSUBPD),
b's' => Some(Ins::ADDSUBPS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'b' => match rstr[1] {b'l' => match rstr[2] {b'e' => match rstr[3] {b'n' => match rstr[4] {b'd' => match rstr[5] {b'v' => match rstr[6] {b'p' => match rstr[7]{b'd' => Some(Ins::BLENDVPD),
b's' => Some(Ins::BLENDVPS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'i' => match rstr[1] {b'n' => match rstr[2] {b's' => match rstr[3] {b'e' => match rstr[4] {b'r' => match rstr[5] {b't' => match rstr[6] {b'p' => match rstr[7] {b's' => Some(Ins::INSERTPS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'm' => match rstr[1] {b'o' => match rstr[2] {b'v' => match rstr[3]{b'm' => match rstr[4] {b's' => match rstr[5] {b'k' => match rstr[6] {b'p' => match rstr[7] {b'd' => Some(Ins::MOVMSKPD),
_=>None}
_=>None}
_=>None}
_=>None}
b'n' => match rstr[4] {b't' => match rstr[5] {b'd' => match rstr[6] {b'q' => match rstr[7] {b'a' => Some(Ins::MOVNTDQA),
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[4]{b'h' => match rstr[5] {b'd' => match rstr[6] {b'u' => match rstr[7] {b'p' => Some(Ins::MOVSHDUP),
_=>None}
_=>None}
_=>None}
b'l' => match rstr[5] {b'd' => match rstr[6] {b'u' => match rstr[7] {b'p' => Some(Ins::MOVSLDUP),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'r' => match rstr[1] {b's' => match rstr[2] {b't' => match rstr[3] {b'o' => match rstr[4] {b'r' => match rstr[5] {b's' => match rstr[6] {b's' => match rstr[7] {b'p' => Some(Ins::RSTORSSP),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'w' => match rstr[1] {b'r' => match rstr[2]{b'f' => match rstr[3] {b's' => match rstr[4] {b'b' => match rstr[5] {b'a' => match rstr[6] {b's' => match rstr[7] {b'e' => Some(Ins::WRFSBASE),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'g' => match rstr[3] {b's' => match rstr[4] {b'b' => match rstr[5] {b'a' => match rstr[6] {b's' => match rstr[7] {b'e' => Some(Ins::WRGSBASE),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'c' => match rstr[1]{b'v' => match rstr[2] {b't' => match rstr[3]{b'd' => match rstr[4] {b'q' => match rstr[5] {b'2' => match rstr[6] {b'p' => match rstr[7]{b'd' => Some(Ins::CVTDQ2PD),
b's' => Some(Ins::CVTDQ2PS),
_=>None}
_=>None}
_=>None}
_=>None}
b'p' => match rstr[4]{b'd' => match rstr[5] {b'2' => match rstr[6]{b'd' => match rstr[7] {b'q' => Some(Ins::CVTPD2DQ),
_=>None}
b'p' => match rstr[7]{b'i' => Some(Ins::CVTPD2PI),
b's' => Some(Ins::CVTPD2PS),
_=>None}
_=>None}
_=>None}
b'i' => match rstr[5] {b'2' => match rstr[6] {b'p' => match rstr[7]{b'd' => Some(Ins::CVTPI2PD),
b's' => Some(Ins::CVTPI2PS),
_=>None}
_=>None}
_=>None}
b's' => match rstr[5] {b'2' => match rstr[6]{b'd' => match rstr[7] {b'q' => Some(Ins::CVTPS2DQ),
_=>None}
b'p' => match rstr[7]{b'd' => Some(Ins::CVTPS2PD),
b'i' => Some(Ins::CVTPS2PI),
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[4]{b'd' => match rstr[5] {b'2' => match rstr[6] {b's' => match rstr[7]{b'i' => Some(Ins::CVTSD2SI),
b's' => Some(Ins::CVTSD2SS),
_=>None}
_=>None}
_=>None}
b'i' => match rstr[5] {b'2' => match rstr[6] {b's' => match rstr[7]{b'd' => Some(Ins::CVTSI2SD),
b's' => Some(Ins::CVTSI2SS),
_=>None}
_=>None}
_=>None}
b's' => match rstr[5] {b'2' => match rstr[6] {b's' => match rstr[7]{b'd' => Some(Ins::CVTSS2SD),
b'i' => Some(Ins::CVTSS2SI),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'l' => match rstr[2]{b'd' => match rstr[3] {b'e' => match rstr[4] {b'm' => match rstr[5] {b'o' => match rstr[6] {b't' => match rstr[7] {b'e' => Some(Ins::CLDEMOTE),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'r' => match rstr[3] {b's' => match rstr[4] {b's' => match rstr[5] {b'b' => match rstr[6] {b's' => match rstr[7] {b'y' => Some(Ins::CLRSSBSY),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'p' => match rstr[1]{b'a' => match rstr[2] {b'c' => match rstr[3] {b'k' => match rstr[4]{b's' => match rstr[5] {b's' => match rstr[6]{b'd' => match rstr[7] {b'w' => Some(Ins::PACKSSDW),
_=>None}
b'w' => match rstr[7] {b'b' => Some(Ins::PACKSSWB),
_=>None}
_=>None}
_=>None}
b'u' => match rstr[5] {b's' => match rstr[6]{b'd' => match rstr[7] {b'w' => Some(Ins::PACKUSDW),
_=>None}
b'w' => match rstr[7] {b'b' => Some(Ins::PACKUSWB),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'b' => match rstr[2] {b'l' => match rstr[3] {b'e' => match rstr[4] {b'n' => match rstr[5] {b'd' => match rstr[6] {b'v' => match rstr[7] {b'b' => Some(Ins::PBLENDVB),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'm' => match rstr[2] {b'u' => match rstr[3] {b'l' => match rstr[4] {b'h' => match rstr[5] {b'r' => match rstr[6] {b's' => match rstr[7] {b'w' => Some(Ins::PMULHRSW),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[1]{b'e' => match rstr[2] {b'n' => match rstr[3] {b'd' => match rstr[4] {b'u' => match rstr[5] {b'i' => match rstr[6] {b'p' => match rstr[7] {b'i' => Some(Ins::SENDUIPI),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'h' => match rstr[2] {b'a' => match rstr[3] {b'1' => match rstr[4] {b'm' => match rstr[5] {b's' => match rstr[6] {b'g' => match rstr[7]{b'1' => Some(Ins::SHA1MSG1),
b'2' => Some(Ins::SHA1MSG2),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'y' => match rstr[2] {b's' => match rstr[3] {b'e' => match rstr[4] {b'n' => match rstr[5] {b't' => match rstr[6] {b'e' => match rstr[7] {b'r' => Some(Ins::SYSENTER),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'u' => match rstr[1]{b'm' => match rstr[2] {b'o' => match rstr[3] {b'n' => match rstr[4] {b'i' => match rstr[5] {b't' => match rstr[6] {b'o' => match rstr[7] {b'r' => Some(Ins::UMONITOR),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'n' => match rstr[2] {b'p' => match rstr[3] {b'c' => match rstr[4] {b'k' => match rstr[5]{b'h' => match rstr[6] {b'p' => match rstr[7] {b's' => Some(Ins::UNPCKHPS),
_=>None}
_=>None}
b'l' => match rstr[6] {b'p' => match rstr[7] {b's' => Some(Ins::UNPCKLPS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'v' => match rstr[1]{b'l' => match rstr[2] {b'd' => match rstr[3] {b'm' => match rstr[4] {b'x' => match rstr[5] {b'c' => match rstr[6] {b's' => match rstr[7] {b'r' => Some(Ins::VLDMXCSR),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[2] {b't' => match rstr[3] {b'm' => match rstr[4] {b'x' => match rstr[5] {b'c' => match rstr[6] {b's' => match rstr[7] {b'r' => Some(Ins::VSTMXCSR),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'u' => match rstr[2] {b'c' => match rstr[3] {b'o' => match rstr[4] {b'm' => match rstr[5] {b'i' => match rstr[6] {b's' => match rstr[7]{b'd' => Some(Ins::VUCOMISD),
b's' => Some(Ins::VUCOMISS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'z' => match rstr[2] {b'e' => match rstr[3] {b'r' => match rstr[4] {b'o' => match rstr[5] {b'a' => match rstr[6] {b'l' => match rstr[7] {b'l' => Some(Ins::VZEROALL),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'b' => match rstr[2]{b'l' => match rstr[3] {b'e' => match rstr[4] {b'n' => match rstr[5] {b'd' => match rstr[6] {b'p' => match rstr[7]{b'd' => Some(Ins::VBLENDPD),
b's' => Some(Ins::VBLENDPS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'n' => match rstr[3] {b'o' => match rstr[4] {b'i' => match rstr[5] {b'n' => match rstr[6] {b'v' => match rstr[7] {b'd' => Some(Ins::VBNOINVD),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'm' => match rstr[2]{b'o' => match rstr[3] {b'v' => match rstr[4]{b'd' => match rstr[5] {b'd' => match rstr[6] {b'u' => match rstr[7] {b'p' => Some(Ins::VMOVDDUP),
_=>None}
_=>None}
_=>None}
b'h' => match rstr[5] {b'l' => match rstr[6] {b'p' => match rstr[7] {b's' => Some(Ins::VMOVHLPS),
_=>None}
_=>None}
_=>None}
b'l' => match rstr[5] {b'h' => match rstr[6] {b'p' => match rstr[7] {b's' => Some(Ins::VMOVLHPS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'p' => match rstr[3] {b's' => match rstr[4] {b'a' => match rstr[5] {b'd' => match rstr[6] {b'b' => match rstr[7] {b'w' => Some(Ins::VMPSADBW),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'p' => match rstr[2]{b'b' => match rstr[3] {b'l' => match rstr[4] {b'e' => match rstr[5] {b'n' => match rstr[6] {b'd' => match rstr[7] {b'w' => Some(Ins::VPBLENDW),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'c' => match rstr[3] {b'm' => match rstr[4] {b'p' => match rstr[5]{b'e' => match rstr[6] {b'q' => match rstr[7]{b'b' => Some(Ins::VPCMPEQB),
b'd' => Some(Ins::VPCMPEQD),
b'q' => Some(Ins::VPCMPEQQ),
b'w' => Some(Ins::VPCMPEQW),
_=>None}
_=>None}
b'g' => match rstr[6] {b't' => match rstr[7]{b'b' => Some(Ins::VPCMPGTB),
b'd' => Some(Ins::VPCMPGTD),
b'q' => Some(Ins::VPCMPGTQ),
b'w' => Some(Ins::VPCMPGTW),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[3] {b'u' => match rstr[4] {b'b' => match rstr[5] {b'u' => match rstr[6] {b's' => match rstr[7]{b'b' => Some(Ins::VPSUBUSB),
b'w' => Some(Ins::VPSUBUSW),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'a' => match rstr[3]{b'd' => match rstr[4] {b'd' => match rstr[5] {b'u' => match rstr[6] {b's' => match rstr[7]{b'b' => Some(Ins::VPADDUSB),
b'w' => Some(Ins::VPADDUSW),
_=>None}
_=>None}
_=>None}
_=>None}
b'l' => match rstr[4] {b'i' => match rstr[5] {b'g' => match rstr[6] {b'n' => match rstr[7] {b'r' => Some(Ins::VPALIGNR),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'm' => match rstr[3]{b'a' => match rstr[4] {b'd' => match rstr[5] {b'd' => match rstr[6] {b'w' => match rstr[7] {b'd' => Some(Ins::VPMADDWD),
_=>None}
_=>None}
_=>None}
_=>None}
b'u' => match rstr[4] {b'l' => match rstr[5]{b'h' => match rstr[6] {b'u' => match rstr[7] {b'w' => Some(Ins::VPMULHUW),
_=>None}
_=>None}
b'u' => match rstr[6] {b'd' => match rstr[7] {b'q' => Some(Ins::VPMULUDQ),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'r' => match rstr[2]{b'o' => match rstr[3] {b'u' => match rstr[4] {b'n' => match rstr[5] {b'd' => match rstr[6]{b'p' => match rstr[7]{b'd' => Some(Ins::VROUNDPD),
b's' => Some(Ins::VROUNDPS),
_=>None}
b's' => match rstr[7]{b'd' => Some(Ins::VROUNDSD),
b's' => Some(Ins::VROUNDSS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[3] {b'q' => match rstr[4] {b'r' => match rstr[5] {b't' => match rstr[6]{b'p' => match rstr[7] {b's' => Some(Ins::VRSQRTPS),
_=>None}
b's' => match rstr[7] {b's' => Some(Ins::VRSQRTSS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'x' => match rstr[1]{b'a' => match rstr[2] {b'c' => match rstr[3] {b'q' => match rstr[4] {b'u' => match rstr[5] {b'i' => match rstr[6] {b'r' => match rstr[7] {b'e' => Some(Ins::XACQUIRE),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'r' => match rstr[2] {b'e' => match rstr[3] {b'l' => match rstr[4] {b'e' => match rstr[5] {b'a' => match rstr[6] {b's' => match rstr[7] {b'e' => Some(Ins::XRELEASE),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[2] {b'a' => match rstr[3] {b'v' => match rstr[4] {b'e' => match rstr[5]{b'c' => match rstr[6] {b'6' => match rstr[7] {b'4' => Some(Ins::XSAVEC64),
_=>None}
_=>None}
b'o' => match rstr[6] {b'p' => match rstr[7] {b't' => Some(Ins::XSAVEOPT),
_=>None}
_=>None}
b's' => match rstr[6] {b'6' => match rstr[7] {b'4' => Some(Ins::XSAVES64),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}9 => match rstr[0] {b'e' => match rstr[1] {b'x' => match rstr[2] {b't' => match rstr[3] {b'r' => match rstr[4] {b'a' => match rstr[5] {b'c' => match rstr[6] {b't' => match rstr[7] {b'p' => match rstr[8] {b's' => Some(Ins::EXTRACTPS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'c' => match rstr[1]{b'm' => match rstr[2] {b'p' => match rstr[3] {b'x' => match rstr[4] {b'c' => match rstr[5] {b'h' => match rstr[6] {b'g' => match rstr[7] {b'8' => match rstr[8] {b'b' => Some(Ins::CMPXCHG8B),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'v' => match rstr[2] {b't' => match rstr[3] {b't' => match rstr[4]{b'p' => match rstr[5]{b'd' => match rstr[6] {b'2' => match rstr[7]{b'd' => match rstr[8] {b'q' => Some(Ins::CVTTPD2DQ),
_=>None}
b'p' => match rstr[8] {b'i' => Some(Ins::CVTTPD2PI),
_=>None}
_=>None}
_=>None}
b's' => match rstr[6] {b'2' => match rstr[7]{b'd' => match rstr[8] {b'q' => Some(Ins::CVTTPS2DQ),
_=>None}
b'p' => match rstr[8] {b'i' => Some(Ins::CVTTPS2PI),
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[5]{b'd' => match rstr[6] {b'2' => match rstr[7] {b's' => match rstr[8] {b'i' => Some(Ins::CVTTSD2SI),
_=>None}
_=>None}
_=>None}
b's' => match rstr[6] {b'2' => match rstr[7] {b's' => match rstr[8] {b'i' => Some(Ins::CVTTSS2SI),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'p' => match rstr[1]{b'm' => match rstr[2] {b'a' => match rstr[3] {b'd' => match rstr[4] {b'd' => match rstr[5] {b'u' => match rstr[6] {b'b' => match rstr[7] {b's' => match rstr[8] {b'w' => Some(Ins::PMADDUBSW),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'r' => match rstr[2] {b'e' => match rstr[3] {b'f' => match rstr[4] {b'e' => match rstr[5] {b't' => match rstr[6] {b'c' => match rstr[7] {b'h' => match rstr[8]{b'0' => Some(Ins::PREFETCH0),
b'1' => Some(Ins::PREFETCH1),
b'2' => Some(Ins::PREFETCH2),
b'a' => Some(Ins::PREFETCHA),
b'w' => Some(Ins::PREFETCHW),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'u' => match rstr[2] {b'n' => match rstr[3] {b'p' => match rstr[4] {b'c' => match rstr[5] {b'k' => match rstr[6]{b'h' => match rstr[7]{b'b' => match rstr[8] {b'w' => Some(Ins::PUNPCKHBW),
_=>None}
b'd' => match rstr[8] {b'q' => Some(Ins::PUNPCKHDQ),
_=>None}
b'w' => match rstr[8] {b'd' => Some(Ins::PUNPCKHWD),
_=>None}
_=>None}
b'l' => match rstr[7]{b'b' => match rstr[8] {b'w' => Some(Ins::PUNPCKLBW),
_=>None}
b'd' => match rstr[8] {b'q' => Some(Ins::PUNPCKLDQ),
_=>None}
b'w' => match rstr[8] {b'd' => Some(Ins::PUNPCKLWD),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'c' => match rstr[2]{b'l' => match rstr[3] {b'm' => match rstr[4] {b'u' => match rstr[5] {b'l' => match rstr[6] {b'q' => match rstr[7] {b'd' => match rstr[8] {b'q' => Some(Ins::PCLMULQDQ),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'm' => match rstr[3] {b'p' => match rstr[4]{b'e' => match rstr[5] {b's' => match rstr[6] {b't' => match rstr[7] {b'r' => match rstr[8]{b'i' => Some(Ins::PCMPESTRI),
b'm' => Some(Ins::PCMPESTRM),
_=>None}
_=>None}
_=>None}
_=>None}
b'i' => match rstr[5] {b's' => match rstr[6] {b't' => match rstr[7] {b'r' => match rstr[8]{b'i' => Some(Ins::PCMPISTRI),
b'm' => Some(Ins::PCMPISTRM),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[1]{b'e' => match rstr[2] {b'r' => match rstr[3] {b'i' => match rstr[4] {b'a' => match rstr[5] {b'l' => match rstr[6] {b'i' => match rstr[7] {b'z' => match rstr[8] {b'e' => Some(Ins::SERIALIZE),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'h' => match rstr[2] {b'a' => match rstr[3] {b'1' => match rstr[4]{b'n' => match rstr[5] {b'e' => match rstr[6] {b'x' => match rstr[7] {b't' => match rstr[8] {b'e' => Some(Ins::SHA1NEXTE),
_=>None}
_=>None}
_=>None}
_=>None}
b'r' => match rstr[5] {b'n' => match rstr[6] {b'd' => match rstr[7] {b's' => match rstr[8] {b'4' => Some(Ins::SHA1RNDS4),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'v' => match rstr[1]{b'a' => match rstr[2] {b'd' => match rstr[3] {b'd' => match rstr[4] {b's' => match rstr[5] {b'u' => match rstr[6] {b'b' => match rstr[7] {b'p' => match rstr[8]{b'd' => Some(Ins::VADDSUBPD),
b's' => Some(Ins::VADDSUBPS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'b' => match rstr[2] {b'l' => match rstr[3] {b'e' => match rstr[4] {b'n' => match rstr[5] {b'd' => match rstr[6] {b'v' => match rstr[7] {b'p' => match rstr[8]{b'd' => Some(Ins::VBLENDVPD),
b's' => Some(Ins::VBLENDVPS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'c' => match rstr[2] {b'v' => match rstr[3] {b't' => match rstr[4]{b'd' => match rstr[5] {b'q' => match rstr[6] {b'2' => match rstr[7] {b'p' => match rstr[8]{b'd' => Some(Ins::VCVTDQ2PD),
b's' => Some(Ins::VCVTDQ2PS),
_=>None}
_=>None}
_=>None}
_=>None}
b'p' => match rstr[5]{b'd' => match rstr[6] {b'2' => match rstr[7]{b'd' => match rstr[8] {b'q' => Some(Ins::VCVTPD2DQ),
_=>None}
b'p' => match rstr[8] {b's' => Some(Ins::VCVTPD2PS),
_=>None}
_=>None}
_=>None}
b's' => match rstr[6] {b'2' => match rstr[7]{b'd' => match rstr[8] {b'q' => Some(Ins::VCVTPS2DQ),
_=>None}
b'p' => match rstr[8] {b'd' => Some(Ins::VCVTPS2PD),
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[5]{b'd' => match rstr[6] {b'2' => match rstr[7] {b's' => match rstr[8]{b'i' => Some(Ins::VCVTSD2SI),
b's' => Some(Ins::VCVTSD2SS),
_=>None}
_=>None}
_=>None}
b'i' => match rstr[6] {b'2' => match rstr[7] {b's' => match rstr[8]{b'd' => Some(Ins::VCVTSI2SD),
b's' => Some(Ins::VCVTSI2SS),
_=>None}
_=>None}
_=>None}
b's' => match rstr[6] {b'2' => match rstr[7] {b's' => match rstr[8]{b'd' => Some(Ins::VCVTSS2SD),
b'i' => Some(Ins::VCVTSS2SI),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'i' => match rstr[2] {b'n' => match rstr[3] {b's' => match rstr[4] {b'e' => match rstr[5] {b'r' => match rstr[6] {b't' => match rstr[7] {b'p' => match rstr[8] {b's' => Some(Ins::VINSERTPS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'm' => match rstr[2] {b'o' => match rstr[3] {b'v' => match rstr[4]{b'm' => match rstr[5] {b's' => match rstr[6] {b'k' => match rstr[7] {b'p' => match rstr[8]{b'd' => Some(Ins::VMOVMSKPD),
b's' => Some(Ins::VMOVMSKPS),
_=>None}
_=>None}
_=>None}
_=>None}
b'n' => match rstr[5] {b't' => match rstr[6] {b'd' => match rstr[7] {b'q' => match rstr[8] {b'a' => Some(Ins::VMOVNTDQA),
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[5]{b'h' => match rstr[6] {b'd' => match rstr[7] {b'u' => match rstr[8] {b'p' => Some(Ins::VMOVSHDUP),
_=>None}
_=>None}
_=>None}
b'l' => match rstr[6] {b'd' => match rstr[7] {b'u' => match rstr[8] {b'p' => Some(Ins::VMOVSLDUP),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'u' => match rstr[2] {b'n' => match rstr[3] {b'p' => match rstr[4] {b'c' => match rstr[5] {b'k' => match rstr[6]{b'h' => match rstr[7] {b'p' => match rstr[8] {b's' => Some(Ins::VUNPCKHPS),
_=>None}
_=>None}
b'l' => match rstr[7] {b'p' => match rstr[8] {b's' => Some(Ins::VUNPCKLPS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'p' => match rstr[2]{b'a' => match rstr[3] {b'c' => match rstr[4] {b'k' => match rstr[5]{b's' => match rstr[6] {b's' => match rstr[7]{b'd' => match rstr[8] {b'w' => Some(Ins::VPACKSSDW),
_=>None}
b'w' => match rstr[8] {b'b' => Some(Ins::VPACKSSWB),
_=>None}
_=>None}
_=>None}
b'u' => match rstr[6] {b's' => match rstr[7]{b'd' => match rstr[8] {b'w' => Some(Ins::VPACKUSDW),
_=>None}
b'w' => match rstr[8] {b'b' => Some(Ins::VPACKUSWB),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'b' => match rstr[3] {b'l' => match rstr[4] {b'e' => match rstr[5] {b'n' => match rstr[6] {b'd' => match rstr[7] {b'v' => match rstr[8] {b'b' => Some(Ins::VPBLENDVB),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'e' => match rstr[3] {b'r' => match rstr[4] {b'm' => match rstr[5] {b'i' => match rstr[6] {b'l' => match rstr[7] {b'p' => match rstr[8]{b'd' => Some(Ins::VPERMILPD),
b's' => Some(Ins::VPERMILPS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'm' => match rstr[3] {b'u' => match rstr[4] {b'l' => match rstr[5] {b'h' => match rstr[6] {b'r' => match rstr[7] {b's' => match rstr[8] {b'w' => Some(Ins::VPMULHRSW),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'x' => match rstr[1]{b'r' => match rstr[2]{b'e' => match rstr[3] {b's' => match rstr[4] {b'l' => match rstr[5] {b'd' => match rstr[6] {b't' => match rstr[7] {b'r' => match rstr[8] {b'k' => Some(Ins::XRESLDTRK),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[3] {b't' => match rstr[4] {b'o' => match rstr[5] {b'r' => match rstr[6] {b's' => match rstr[7] {b'6' => match rstr[8] {b'4' => Some(Ins::XRSTORS64),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[2] {b'u' => match rstr[3] {b's' => match rstr[4] {b'l' => match rstr[5] {b'd' => match rstr[6] {b't' => match rstr[7] {b'r' => match rstr[8] {b'k' => Some(Ins::XSUSLDTRK),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}10 => match rstr[0] {b'a' => match rstr[1] {b'e' => match rstr[2] {b's' => match rstr[3]{b'd' => match rstr[4] {b'e' => match rstr[5] {b'c' => match rstr[6] {b'l' => match rstr[7] {b'a' => match rstr[8] {b's' => match rstr[9] {b't' => Some(Ins::AESDECLAST),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'e' => match rstr[4] {b'n' => match rstr[5] {b'c' => match rstr[6] {b'l' => match rstr[7] {b'a' => match rstr[8] {b's' => match rstr[9] {b't' => Some(Ins::AESENCLAST),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'c' => match rstr[1] {b'm' => match rstr[2] {b'p' => match rstr[3] {b'x' => match rstr[4] {b'c' => match rstr[5] {b'h' => match rstr[6] {b'g' => match rstr[7] {b'1' => match rstr[8] {b'6' => match rstr[9] {b'b' => Some(Ins::CMPXCHG16B),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'm' => match rstr[1] {b'a' => match rstr[2] {b's' => match rstr[3] {b'k' => match rstr[4] {b'm' => match rstr[5] {b'o' => match rstr[6] {b'v' => match rstr[7] {b'd' => match rstr[8] {b'q' => match rstr[9] {b'u' => Some(Ins::MASKMOVDQU),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[1] {b'h' => match rstr[2] {b'a' => match rstr[3] {b'2' => match rstr[4] {b'5' => match rstr[5] {b'6' => match rstr[6] {b'm' => match rstr[7] {b's' => match rstr[8] {b'g' => match rstr[9]{b'1' => Some(Ins::SHA256MSG1),
b'2' => Some(Ins::SHA256MSG2),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'x' => match rstr[1] {b's' => match rstr[2] {b'a' => match rstr[3] {b'v' => match rstr[4] {b'e' => match rstr[5] {b'o' => match rstr[6] {b'p' => match rstr[7] {b't' => match rstr[8] {b'6' => match rstr[9] {b'4' => Some(Ins::XSAVEOPT64),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'p' => match rstr[1]{b'h' => match rstr[2] {b'm' => match rstr[3] {b'i' => match rstr[4] {b'n' => match rstr[5] {b'p' => match rstr[6] {b'o' => match rstr[7] {b's' => match rstr[8] {b'u' => match rstr[9] {b'w' => Some(Ins::PHMINPOSUW),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'u' => match rstr[2] {b'n' => match rstr[3] {b'p' => match rstr[4] {b'c' => match rstr[5] {b'k' => match rstr[6]{b'h' => match rstr[7] {b'q' => match rstr[8] {b'd' => match rstr[9] {b'q' => Some(Ins::PUNPCKHQDQ),
_=>None}
_=>None}
_=>None}
b'l' => match rstr[7] {b'q' => match rstr[8] {b'd' => match rstr[9] {b'q' => Some(Ins::PUNPCKLQDQ),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'v' => match rstr[1]{b'c' => match rstr[2] {b'v' => match rstr[3] {b't' => match rstr[4] {b't' => match rstr[5]{b'p' => match rstr[6]{b'd' => match rstr[7] {b'2' => match rstr[8] {b'd' => match rstr[9] {b'q' => Some(Ins::VCVTTPD2DQ),
_=>None}
_=>None}
_=>None}
b's' => match rstr[7] {b'2' => match rstr[8] {b'd' => match rstr[9] {b'q' => Some(Ins::VCVTTPS2DQ),
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[6]{b'd' => match rstr[7] {b'2' => match rstr[8] {b's' => match rstr[9] {b'i' => Some(Ins::VCVTTSD2SI),
_=>None}
_=>None}
_=>None}
b's' => match rstr[7] {b'2' => match rstr[8] {b's' => match rstr[9] {b'i' => Some(Ins::VCVTTSS2SI),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'e' => match rstr[2] {b'x' => match rstr[3] {b't' => match rstr[4] {b'r' => match rstr[5] {b'a' => match rstr[6] {b'c' => match rstr[7] {b't' => match rstr[8] {b'p' => match rstr[9] {b's' => Some(Ins::VEXTRACTPS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'z' => match rstr[2] {b'e' => match rstr[3] {b'r' => match rstr[4] {b'o' => match rstr[5] {b'u' => match rstr[6] {b'p' => match rstr[7] {b'p' => match rstr[8] {b'e' => match rstr[9] {b'r' => Some(Ins::VZEROUPPER),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'p' => match rstr[2]{b'e' => match rstr[3] {b'r' => match rstr[4] {b'm' => match rstr[5] {b'2' => match rstr[6]{b'f' => match rstr[7] {b'1' => match rstr[8] {b'2' => match rstr[9] {b'8' => Some(Ins::VPERM2F128),
_=>None}
_=>None}
_=>None}
b'i' => match rstr[7] {b'1' => match rstr[8] {b'2' => match rstr[9] {b'8' => Some(Ins::VPERM2I128),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'u' => match rstr[3] {b'n' => match rstr[4] {b'p' => match rstr[5] {b'c' => match rstr[6] {b'k' => match rstr[7]{b'h' => match rstr[8]{b'b' => match rstr[9] {b'w' => Some(Ins::VPUNPCKHBW),
_=>None}
b'd' => match rstr[9] {b'q' => Some(Ins::VPUNPCKHDQ),
_=>None}
b'w' => match rstr[9] {b'd' => Some(Ins::VPUNPCKHWD),
_=>None}
_=>None}
b'l' => match rstr[8]{b'b' => match rstr[9] {b'w' => Some(Ins::VPUNPCKLBW),
_=>None}
b'd' => match rstr[9] {b'q' => Some(Ins::VPUNPCKLDQ),
_=>None}
b'w' => match rstr[9] {b'd' => Some(Ins::VPUNPCKLWD),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'c' => match rstr[3]{b'l' => match rstr[4] {b'm' => match rstr[5] {b'u' => match rstr[6] {b'l' => match rstr[7] {b'q' => match rstr[8] {b'd' => match rstr[9] {b'q' => Some(Ins::VPCLMULQDQ),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'm' => match rstr[4] {b'p' => match rstr[5]{b'e' => match rstr[6] {b's' => match rstr[7] {b't' => match rstr[8] {b'r' => match rstr[9]{b'i' => Some(Ins::VPCMPESTRI),
b'm' => Some(Ins::VPCMPESTRM),
_=>None}
_=>None}
_=>None}
_=>None}
b'i' => match rstr[6] {b's' => match rstr[7] {b't' => match rstr[8] {b'r' => match rstr[9]{b'i' => Some(Ins::VPCMPISTRI),
b'm' => Some(Ins::VPCMPISTRM),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}11 => match rstr[0] {b's' => match rstr[1] {b'h' => match rstr[2] {b'a' => match rstr[3] {b'2' => match rstr[4] {b'5' => match rstr[5] {b'6' => match rstr[6] {b'r' => match rstr[7] {b'n' => match rstr[8] {b'd' => match rstr[9] {b's' => match rstr[10] {b'2' => Some(Ins::SHA256RNDS2),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'v' => match rstr[1]{b'a' => match rstr[2] {b'e' => match rstr[3] {b's' => match rstr[4]{b'd' => match rstr[5] {b'e' => match rstr[6] {b'c' => match rstr[7] {b'l' => match rstr[8] {b'a' => match rstr[9] {b's' => match rstr[10] {b't' => Some(Ins::VAESDECLAST),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'e' => match rstr[5] {b'n' => match rstr[6] {b'c' => match rstr[7] {b'l' => match rstr[8] {b'a' => match rstr[9] {b's' => match rstr[10] {b't' => Some(Ins::VAESENCLAST),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'f' => match rstr[2] {b'm' => match rstr[3]{b'a' => match rstr[4] {b'd' => match rstr[5] {b'd' => match rstr[6]{b'1' => match rstr[7] {b'3' => match rstr[8] {b'2' => match rstr[9]{b'p' => match rstr[10]{b'd' => Some(Ins::VFMADD132PD),
b's' => Some(Ins::VFMADD132PS),
_=>None}
b's' => match rstr[10]{b'd' => Some(Ins::VFMADD132SD),
b's' => Some(Ins::VFMADD132SS),
_=>None}
_=>None}
_=>None}
_=>None}
b'2' => match rstr[7]{b'1' => match rstr[8] {b'3' => match rstr[9]{b'p' => match rstr[10]{b'd' => Some(Ins::VFMADD213PD),
b's' => Some(Ins::VFMADD213PS),
_=>None}
b's' => match rstr[10]{b'd' => Some(Ins::VFMADD213SD),
b's' => Some(Ins::VFMADD213SS),
_=>None}
_=>None}
_=>None}
b'3' => match rstr[8] {b'1' => match rstr[9]{b'p' => match rstr[10]{b'd' => Some(Ins::VFMADD231PD),
b's' => Some(Ins::VFMADD231PS),
_=>None}
b's' => match rstr[10]{b'd' => Some(Ins::VFMADD231SD),
b's' => Some(Ins::VFMADD231SS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[4] {b'u' => match rstr[5] {b'b' => match rstr[6]{b'1' => match rstr[7] {b'3' => match rstr[8] {b'2' => match rstr[9]{b'p' => match rstr[10]{b'd' => Some(Ins::VFMSUB132PD),
b's' => Some(Ins::VFMSUB132PS),
_=>None}
b's' => match rstr[10]{b'd' => Some(Ins::VFMSUB132SD),
b's' => Some(Ins::VFMSUB132SS),
_=>None}
_=>None}
_=>None}
_=>None}
b'2' => match rstr[7]{b'1' => match rstr[8] {b'3' => match rstr[9]{b'p' => match rstr[10]{b'd' => Some(Ins::VFMSUB213PD),
b's' => Some(Ins::VFMSUB213PS),
_=>None}
b's' => match rstr[10]{b'd' => Some(Ins::VFMSUB213SD),
b's' => Some(Ins::VFMSUB213SS),
_=>None}
_=>None}
_=>None}
b'3' => match rstr[8] {b'1' => match rstr[9]{b'p' => match rstr[10]{b'd' => Some(Ins::VFMSUB231PD),
b's' => Some(Ins::VFMSUB231PS),
_=>None}
b's' => match rstr[10]{b'd' => Some(Ins::VFMSUB231SD),
b's' => Some(Ins::VFMSUB231SS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'i' => match rstr[2] {b'n' => match rstr[3] {b's' => match rstr[4] {b'e' => match rstr[5] {b'r' => match rstr[6] {b't' => match rstr[7] {b'f' => match rstr[8] {b'1' => match rstr[9] {b'2' => match rstr[10] {b'8' => Some(Ins::VINSERTF128),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'p' => match rstr[2] {b'h' => match rstr[3] {b'm' => match rstr[4] {b'i' => match rstr[5] {b'n' => match rstr[6] {b'p' => match rstr[7] {b'o' => match rstr[8] {b's' => match rstr[9] {b'u' => match rstr[10] {b'w' => Some(Ins::VPHMINPOSUW),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}12 => match rstr[0] {b'v' => match rstr[1]{b'b' => match rstr[2] {b'r' => match rstr[3] {b'o' => match rstr[4] {b'a' => match rstr[5] {b'd' => match rstr[6] {b'c' => match rstr[7] {b'a' => match rstr[8] {b's' => match rstr[9] {b't' => match rstr[10] {b's' => match rstr[11]{b'd' => Some(Ins::VBROADCASTSD),
b's' => Some(Ins::VBROADCASTSS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'e' => match rstr[2] {b'x' => match rstr[3] {b't' => match rstr[4] {b'r' => match rstr[5] {b'a' => match rstr[6] {b'c' => match rstr[7] {b't' => match rstr[8] {b'f' => match rstr[9] {b'1' => match rstr[10] {b'2' => match rstr[11] {b'8' => Some(Ins::VEXTRACTF128),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'f' => match rstr[2] {b'n' => match rstr[3] {b'm' => match rstr[4]{b'a' => match rstr[5] {b'd' => match rstr[6] {b'd' => match rstr[7]{b'1' => match rstr[8] {b'3' => match rstr[9] {b'2' => match rstr[10]{b'p' => match rstr[11]{b'd' => Some(Ins::VFNMADD132PD),
b's' => Some(Ins::VFNMADD132PS),
_=>None}
b's' => match rstr[11]{b'd' => Some(Ins::VFNMADD132SD),
b's' => Some(Ins::VFNMADD132SS),
_=>None}
_=>None}
_=>None}
_=>None}
b'2' => match rstr[8]{b'1' => match rstr[9] {b'3' => match rstr[10]{b'p' => match rstr[11]{b'd' => Some(Ins::VFNMADD213PD),
b's' => Some(Ins::VFNMADD213PS),
_=>None}
b's' => match rstr[11]{b'd' => Some(Ins::VFNMADD213SD),
b's' => Some(Ins::VFNMADD213SS),
_=>None}
_=>None}
_=>None}
b'3' => match rstr[9] {b'1' => match rstr[10]{b'p' => match rstr[11]{b'd' => Some(Ins::VFNMADD231PD),
b's' => Some(Ins::VFNMADD231PS),
_=>None}
b's' => match rstr[11]{b'd' => Some(Ins::VFNMADD231SD),
b's' => Some(Ins::VFNMADD231SS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[5] {b'u' => match rstr[6] {b'b' => match rstr[7]{b'1' => match rstr[8] {b'3' => match rstr[9] {b'2' => match rstr[10]{b'p' => match rstr[11]{b'd' => Some(Ins::VFNMSUB132PD),
b's' => Some(Ins::VFNMSUB132PS),
_=>None}
b's' => match rstr[11]{b'd' => Some(Ins::VFNMSUB132SD),
b's' => Some(Ins::VFNMSUB132SS),
_=>None}
_=>None}
_=>None}
_=>None}
b'2' => match rstr[8]{b'1' => match rstr[9] {b'3' => match rstr[10]{b'p' => match rstr[11]{b'd' => Some(Ins::VFNMSUB213PD),
b's' => Some(Ins::VFNMSUB213PS),
_=>None}
b's' => match rstr[11]{b'd' => Some(Ins::VFNMSUB213SD),
b's' => Some(Ins::VFNMSUB213SS),
_=>None}
_=>None}
_=>None}
b'3' => match rstr[9] {b'1' => match rstr[10]{b'p' => match rstr[11]{b'd' => Some(Ins::VFNMSUB231PD),
b's' => Some(Ins::VFNMSUB231PS),
_=>None}
b's' => match rstr[11]{b'd' => Some(Ins::VFNMSUB231SD),
b's' => Some(Ins::VFNMSUB231SS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}14 => match rstr[0] {b'v' => match rstr[1]{b'b' => match rstr[2] {b'r' => match rstr[3] {b'o' => match rstr[4] {b'a' => match rstr[5] {b'd' => match rstr[6] {b'c' => match rstr[7] {b'a' => match rstr[8] {b's' => match rstr[9] {b't' => match rstr[10] {b'f' => match rstr[11] {b'1' => match rstr[12] {b'2' => match rstr[13] {b'8' => Some(Ins::VBROADCASTF128),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b'f' => match rstr[2] {b'm' => match rstr[3]{b'a' => match rstr[4] {b'd' => match rstr[5] {b'd' => match rstr[6] {b's' => match rstr[7] {b'u' => match rstr[8] {b'b' => match rstr[9]{b'1' => match rstr[10] {b'3' => match rstr[11] {b'2' => match rstr[12] {b'p' => match rstr[13]{b'd' => Some(Ins::VFMADDSUB132PD),
b's' => Some(Ins::VFMADDSUB132PS),
_=>None}
_=>None}
_=>None}
_=>None}
b'2' => match rstr[10]{b'1' => match rstr[11] {b'3' => match rstr[12] {b'p' => match rstr[13]{b'd' => Some(Ins::VFMADDSUB213PD),
b's' => Some(Ins::VFMADDSUB213PS),
_=>None}
_=>None}
_=>None}
b'3' => match rstr[11] {b'1' => match rstr[12] {b'p' => match rstr[13]{b'd' => Some(Ins::VFMADDSUB231PD),
b's' => Some(Ins::VFMADDSUB231PS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
b's' => match rstr[4] {b'u' => match rstr[5] {b'b' => match rstr[6] {b'a' => match rstr[7] {b'd' => match rstr[8] {b'd' => match rstr[9]{b'1' => match rstr[10] {b'3' => match rstr[11] {b'2' => match rstr[12] {b'p' => match rstr[13]{b'd' => Some(Ins::VFMSUBADD132PD),
b's' => Some(Ins::VFMSUBADD132PS),
_=>None}
_=>None}
_=>None}
_=>None}
b'2' => match rstr[10]{b'1' => match rstr[11] {b'3' => match rstr[12] {b'p' => match rstr[13]{b'd' => Some(Ins::VFMSUBADD213PD),
b's' => Some(Ins::VFMSUBADD213PS),
_=>None}
_=>None}
_=>None}
b'3' => match rstr[11] {b'1' => match rstr[12] {b'p' => match rstr[13]{b'd' => Some(Ins::VFMSUBADD231PD),
b's' => Some(Ins::VFMSUBADD231PS),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}15 => match rstr[0] {b'a' => match rstr[1] {b'e' => match rstr[2] {b's' => match rstr[3] {b'k' => match rstr[4] {b'e' => match rstr[5] {b'y' => match rstr[6] {b'g' => match rstr[7] {b'e' => match rstr[8] {b'n' => match rstr[9] {b'a' => match rstr[10] {b's' => match rstr[11] {b's' => match rstr[12] {b'i' => match rstr[13] {b's' => match rstr[14] {b't' => Some(Ins::AESKEYGENASSIST),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}16 => match rstr[0] {b'v' => match rstr[1] {b'a' => match rstr[2] {b'e' => match rstr[3] {b's' => match rstr[4] {b'k' => match rstr[5] {b'e' => match rstr[6] {b'y' => match rstr[7] {b'g' => match rstr[8] {b'e' => match rstr[9] {b'n' => match rstr[10] {b'a' => match rstr[11] {b's' => match rstr[12] {b's' => match rstr[13] {b'i' => match rstr[14] {b's' => match rstr[15] {b't' => Some(Ins::VAESKEYGENASSIST),
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
_=>None}
		_ => None,
	}
}